{
  "hash": "93c6b97d68781f30a0b1ec941e1e32b4",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Analysis Code for the RoCSI-CPR study\"\nauthor: \"Nathan Hubot, Susan Evans, Julie Robidart\"\nformat:\n  html:\n    toc: true\n    toc-depth: 3\n    theme: cosmo\neditor: source\nexecute:\n  echo: true\n  warning: false\n  message: false\n  cache: true\n---\n\n# 🧬 Overview of Sequencing & Experimental Design\n\nThis report summarises the **two metabarcoding workflows** applied to the RoCSI-CPR eDNA samples:\n\n-   **18S rRNA V9 region** (targeting phytoplankton)\n-   **COI mitochondrial region** (targeting zooplankton)\n\nBoth datasets were sequenced at the\\\n**Centre for Genomic Research (CGR), University of Liverpool.**\n\n## 📊 Sequencing Summary\n\n| Feature | **18S rRNA V9** | **COI (metazoans)** |\n|-----------------|-------------------------|-------------------------------|\n| **SSP ID** | [SSP202877](https://cgr.liv.ac.uk/illum/SSP202877_b388934ddf413642/) | [SSP200993](https://cgr.liv.ac.uk/illum/SSP200993_bbba6061877a5e12) |\n| **Purchase order** | 203631529 | P10817-5 |\n| **Sequencing platform** | Illumina MiSeq v2 (2×150 bp) | Illumina MiSeq v2 (2×250 bp) |\n| **Target region** | 18S V9 (1389F–1510R) | COI Leray fragment (m1COIintF–jgHCO2198) |\n| **Expected amplicon size** | \\~121 bp | \\~313 bp |\n| **Raw read depth (mean)** | \\~150k | \\~200k |\n| **Pre-trimming QC** | Cutadapt v4.5 | Cutadapt v1.2.1 + Sickle v1.200 |\n| **Downstream processing** | Cutadapt → DADA2 → MZG 18S | Cutadapt → DADA2 → MZG COI |\n\n------------------------------------------------------------------------\n\n# 🧬 Primer Sets (with CGR Overhangs)\n\n## 18S V9 Primers\n\n-   **Forward:**\\\n    5′ [ACACTCTTTCCCTACACGACGCTCTTCCGATCTNNNNN]{style=\"color:#2E86C1;font-weight:bold;\"}\\\n    [TTGTACACACCGCCC]{style=\"color:#C0392B;font-weight:bold;\"} 3′\\\n    *(CGR overhang + spacer in blue; 18S primer in red)*\n\n-   **Reverse:**\\\n    5′ [GTGACTGGAGTTCAGACGTGTGCTCTTCCGATCT]{style=\"color:#2E86C1;font-weight:bold;\"}\\\n    [CCTTCYGCAGGTTCACCTAC]{style=\"color:#C0392B;font-weight:bold;\"} 3′\n\n------------------------------------------------------------------------\n\n## COI Primers\n\n-   **Forward:**\\\n    5′ [ACACTCTTTCCCTACACGACGCTCTTCCGATCTNNNNN]{style=\"color:#2E86C1;font-weight:bold;\"}\\\n    [GGWACWGGWTGAACWGTWTAYCCYCC]{style=\"color:#C0392B;font-weight:bold;\"} 3′\\\n    *(m1COIintF)*\n\n-   **Reverse:**\\\n    5′ [GTGACTGGAGTTCAGACGTGTGCTCTTCCGATCT]{style=\"color:#2E86C1;font-weight:bold;\"}\\\n    [TAIACYTCIGGRTGICCRAARAAYCA]{style=\"color:#C0392B;font-weight:bold;\"} 3′\\\n    *(jgHCO2198)*\n\n------------------------------------------------------------------------\n\n# 🔧 Bioinformatic Workflow Overview\n\nBoth markers follow the same general pipeline:\n\n1.  **Primer removal** (Cutadapt)\\\n2.  **Quality filtering** (DADA2)\\\n3.  **Error learning and denoising** (DADA2)\\\n4.  **Read merging** (DADA2)\\\n5.  **Chimera removal** (DADA2)\\\n6.  **Taxonomic assignment: ** (DADA2)\n    -   18S → *MZG 18S “All Microbes + Protists”, Mode-A* reference database\\\n    -   COI → *MZG COI “All Invertebrates”, Mode-A* reference database\n\nFor each step, differences between the two pipelines are shown.\n\n------------------------------------------------------------------------\n\n# 1️⃣ Primer Removal with Cutadapt\n\n### 🔹 Summary of Cutadapt parameters used\n\n| Parameter | **18S** | **COI** |\n|--------------------------|-----------------------|-----------------------|\n| Forward primer (`-g`) | TTGTACACACCGCCC | GGWACWGGWTGAACWGTWTAYCCYCC |\n| Reverse primer (`-G`) | CCTTCYGCAGGTTCACCTAC | TANACYTCNGGRTGNCCRAARAAYCA |\n| `--match-read-wildcards` | ✔️ | ✔️ |\n| Minimum overlap | **10** | **20** |\n| Max error rate (`-e`) | **0.15** | **0.20** |\n| `--discard-untrimmed` | ✔️ | ✔️ |\n| `--minimum-length` | 80 bp | 200 bp |\n| Pre-processing by CGR | Adapters trimmed via Cutadapt 4.5 | Adapters trimmed (Cutadapt v1.2.1) + Sickle quality filtering |\n\n------------------------------------------------------------------------\n\n### 🔹 Unified Cutadapt description\n\nBoth datasets used a looping bash command of the form:\n\n``` bash\n\ncutadapt\\\n  -g <forward_primer> \\\n  -G <reverse_primer> \\\n  --match-read-wildcards \\\n  --overlap <OV> \\\n  -e <ERROR> \\\n  --pair-filter=both \\\n  --discard-untrimmed \\\n  --cores=0 \\\n  -o $out1 -p $out2 \\\n  $f $r\n\n```\nWhere <OV> and <ERROR> differ between markers (see table above).\n\n# 2️⃣ DADA2 Processing\n\n### 🔹 Summary of Cutadapt parameters used\n\n| Parameters                | **18S**    | **COI**                             |\n| ------------------------- | ---------- | ----------------------------------- |\n| `truncLen`                | c(130,120) | c(210,210)                          |\n| `maxEE`                   | c(2,3)     | c(2,3)                              |\n| `minLen`                  | 80         | 200                                 |\n| `minOverlap` (mergePairs) | 30         | 90                                  |\n| Ref database              | MZG 18S    | MZG COI                             |\n\n::: {.callout-note title=\"MZG Reference databases\"}\n| Marker  | Database                               | Notes                                        |\n| ------- | -------------------------------------- | -------------------------------------------- |\n| **18S** | `MZGdada2-18s__T2000000__o00__A.fastq` | phytoplankton --> \"All Microbes + Protists\", mode-A    |\n| **COI** | `MZGdada2-coi__T4000000__o00__A.fastq` | zooplankton --> “All invertebrates”, mode-A          |\nsource: https://metazoogene.org/mzgdb/atlas/html-src/data__T4000000__o00.html\n:::\n\n### 🔹 Unified DADA2 description\n\nBoth datasets were processed with the standard DADA2 workflow:\n\n``` r\n\n# Filtering and trimming (R1/R2 after cutadapt)\nfiltered_out <- filterAndTrim(\n  fwd  = forward_reads,\n  filt = filtered_forward_reads,\n  rev  = reverse_reads,\n  filt.rev = filtered_reverse_reads,\n  truncLen  = <MARKER_SPECIFIC>,   # see table above\n  maxEE     = c(2, 3),             # expected errors (stricter for R1)\n  maxN      = 0,                   # discard reads with Ns\n  rm.phix   = TRUE,                # remove PhiX reads\n  minLen    = <MINLEN>,            # marker-specific minimum length\n  multithread = TRUE\n)\n\n# Error learning\nerrF <- learnErrors(filtered_forward_reads, multithread=TRUE)\nerrR <- learnErrors(filtered_reverse_reads, multithread=TRUE)\n\n# Dereplication\nderepF <- derepFastq(filtered_forward_reads)\nderepR <- derepFastq(filtered_reverse_reads)\n\n# ASV inference\ndadaF <- dada(derepF, err=errF, pool=\"pseudo\")\ndadaR <- dada(derepR, err=errR, pool=\"pseudo\")\n\n# Merging\nmerged <- mergePairs(dadaF, derepF, dadaR, derepR,\n                     minOverlap = <MARKER_SPECIFIC>,\n                     trimOverhang = TRUE)\n\n# ASV table\nseqtab <- makeSequenceTable(merged)\n\n# Chimera removal\nseqtab.nochim <- removeBimeraDenovo(seqtab, method=\"consensus\")\n\n# Taxonomic Assignment\ntaxa <- assignTaxonomy(\n  seqtab.nochim,\n  refFasta = <REF_FASTA>,\n  multithread = TRUE\n)\n\n```\n\n::: {.callout-note title=\"Note\"}\nFor 18S, shorter reads (150 bp) and a very short amplicon (~121 bp) justify relatively short truncLen (130, 120) and minLen = 80.\nFor COI, the longer amplicon fragment (~313 bp) and 2×250 bp reads allow more aggressive truncation (210, 210) with large overlap (90) and a higher minLen = 200 to remove spurious short fragments.\n:::\n\n# 🔍 Read Tracking Summary\n\nThe following table summarizes read counts at each step of the DADA2 pipeline:\n\n\n::: {.cell}\n::: {.cell-output-display}\n`````{=html}\n<div style=\"border: 1px solid #ddd; padding: 0px; overflow-y: scroll; height:400px; overflow-x: scroll; width:100%; \"><table class=\"table table-striped table-hover table-condensed\" style=\"width: auto !important; margin-left: auto; margin-right: auto;\">\n<caption>DADA2 Counts for 18S and COI</caption>\n <thead>\n<tr>\n<th style=\"empty-cells: hide;border-bottom:hidden;position: sticky; top:0; background-color: #FFFFFF;\" colspan=\"1\"></th>\n<th style=\"border-bottom:hidden;padding-bottom:0; padding-left:3px;padding-right:3px;text-align: center; position: sticky; top:0; background-color: #FFFFFF;\" colspan=\"4\"><div style=\"border-bottom: 1px solid #ddd; padding-bottom: 5px; \">18S</div></th>\n<th style=\"border-bottom:hidden;padding-bottom:0; padding-left:3px;padding-right:3px;text-align: center; position: sticky; top:0; background-color: #FFFFFF;\" colspan=\"4\"><div style=\"border-bottom: 1px solid #ddd; padding-bottom: 5px; \">COI</div></th>\n</tr>\n  <tr>\n   <th style=\"text-align:left;position: sticky; top:0; background-color: #FFFFFF;\"> sample </th>\n   <th style=\"text-align:right;position: sticky; top:0; background-color: #FFFFFF;\"> input </th>\n   <th style=\"text-align:right;position: sticky; top:0; background-color: #FFFFFF;\"> filtered </th>\n   <th style=\"text-align:right;position: sticky; top:0; background-color: #FFFFFF;\"> nonchim </th>\n   <th style=\"text-align:right;position: sticky; top:0; background-color: #FFFFFF;\"> reads_retained (%) </th>\n   <th style=\"text-align:right;position: sticky; top:0; background-color: #FFFFFF;\"> input </th>\n   <th style=\"text-align:right;position: sticky; top:0; background-color: #FFFFFF;\"> filtered </th>\n   <th style=\"text-align:right;position: sticky; top:0; background-color: #FFFFFF;\"> nonchim </th>\n   <th style=\"text-align:right;position: sticky; top:0; background-color: #FFFFFF;\"> reads_retained (%) </th>\n  </tr>\n </thead>\n<tbody>\n  <tr>\n   <td style=\"text-align:left;\"> 01-CPR_1_ID_1_ </td>\n   <td style=\"text-align:right;\"> 148213 </td>\n   <td style=\"text-align:right;\"> 128862 </td>\n   <td style=\"text-align:right;\"> 126330 </td>\n   <td style=\"text-align:right;\"> 85.2 </td>\n   <td style=\"text-align:right;\"> 144059 </td>\n   <td style=\"text-align:right;\"> 139400 </td>\n   <td style=\"text-align:right;\"> 104643 </td>\n   <td style=\"text-align:right;\"> 72.6 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> 02-CPR_1_ID_2_ </td>\n   <td style=\"text-align:right;\"> 121841 </td>\n   <td style=\"text-align:right;\"> 105245 </td>\n   <td style=\"text-align:right;\"> 103807 </td>\n   <td style=\"text-align:right;\"> 85.2 </td>\n   <td style=\"text-align:right;\"> 91034 </td>\n   <td style=\"text-align:right;\"> 86400 </td>\n   <td style=\"text-align:right;\"> 82657 </td>\n   <td style=\"text-align:right;\"> 90.8 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> 03-CPR_1_ID_3_ </td>\n   <td style=\"text-align:right;\"> 117632 </td>\n   <td style=\"text-align:right;\"> 96408 </td>\n   <td style=\"text-align:right;\"> 94945 </td>\n   <td style=\"text-align:right;\"> 80.7 </td>\n   <td style=\"text-align:right;\"> 77206 </td>\n   <td style=\"text-align:right;\"> 75069 </td>\n   <td style=\"text-align:right;\"> 65275 </td>\n   <td style=\"text-align:right;\"> 84.5 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> 04-CPR_1_ID_4_ </td>\n   <td style=\"text-align:right;\"> 170195 </td>\n   <td style=\"text-align:right;\"> 135708 </td>\n   <td style=\"text-align:right;\"> 133962 </td>\n   <td style=\"text-align:right;\"> 78.7 </td>\n   <td style=\"text-align:right;\"> 99005 </td>\n   <td style=\"text-align:right;\"> 95927 </td>\n   <td style=\"text-align:right;\"> 88038 </td>\n   <td style=\"text-align:right;\"> 88.9 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> 05-CPR_1_ID_5_ </td>\n   <td style=\"text-align:right;\"> 139036 </td>\n   <td style=\"text-align:right;\"> 124966 </td>\n   <td style=\"text-align:right;\"> 123177 </td>\n   <td style=\"text-align:right;\"> 88.6 </td>\n   <td style=\"text-align:right;\"> 143700 </td>\n   <td style=\"text-align:right;\"> 136891 </td>\n   <td style=\"text-align:right;\"> 130456 </td>\n   <td style=\"text-align:right;\"> 90.8 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> 06-CPR_1_ID_7_ </td>\n   <td style=\"text-align:right;\"> 189844 </td>\n   <td style=\"text-align:right;\"> 172629 </td>\n   <td style=\"text-align:right;\"> 170302 </td>\n   <td style=\"text-align:right;\"> 89.7 </td>\n   <td style=\"text-align:right;\"> 100258 </td>\n   <td style=\"text-align:right;\"> 95319 </td>\n   <td style=\"text-align:right;\"> 91819 </td>\n   <td style=\"text-align:right;\"> 91.6 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> 07-CPR_1_ID_8_ </td>\n   <td style=\"text-align:right;\"> 156940 </td>\n   <td style=\"text-align:right;\"> 134665 </td>\n   <td style=\"text-align:right;\"> 132550 </td>\n   <td style=\"text-align:right;\"> 84.5 </td>\n   <td style=\"text-align:right;\"> 163332 </td>\n   <td style=\"text-align:right;\"> 156331 </td>\n   <td style=\"text-align:right;\"> 150014 </td>\n   <td style=\"text-align:right;\"> 91.8 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> 08-CPR_1_ID_9_ </td>\n   <td style=\"text-align:right;\"> 169359 </td>\n   <td style=\"text-align:right;\"> 155134 </td>\n   <td style=\"text-align:right;\"> 153346 </td>\n   <td style=\"text-align:right;\"> 90.5 </td>\n   <td style=\"text-align:right;\"> 56907 </td>\n   <td style=\"text-align:right;\"> 47951 </td>\n   <td style=\"text-align:right;\"> 46489 </td>\n   <td style=\"text-align:right;\"> 81.7 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> 09-CPR_1_ID_10_ </td>\n   <td style=\"text-align:right;\"> 149202 </td>\n   <td style=\"text-align:right;\"> 134894 </td>\n   <td style=\"text-align:right;\"> 132964 </td>\n   <td style=\"text-align:right;\"> 89.1 </td>\n   <td style=\"text-align:right;\"> 164215 </td>\n   <td style=\"text-align:right;\"> 149580 </td>\n   <td style=\"text-align:right;\"> 141147 </td>\n   <td style=\"text-align:right;\"> 86.0 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> 10-CPR_1_ID_12_ </td>\n   <td style=\"text-align:right;\"> 133358 </td>\n   <td style=\"text-align:right;\"> 109353 </td>\n   <td style=\"text-align:right;\"> 108318 </td>\n   <td style=\"text-align:right;\"> 81.2 </td>\n   <td style=\"text-align:right;\"> 82507 </td>\n   <td style=\"text-align:right;\"> 79597 </td>\n   <td style=\"text-align:right;\"> 75675 </td>\n   <td style=\"text-align:right;\"> 91.7 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> 11-CPR_1_ID_13_ </td>\n   <td style=\"text-align:right;\"> 159171 </td>\n   <td style=\"text-align:right;\"> 119466 </td>\n   <td style=\"text-align:right;\"> 118219 </td>\n   <td style=\"text-align:right;\"> 74.3 </td>\n   <td style=\"text-align:right;\"> 133207 </td>\n   <td style=\"text-align:right;\"> 128803 </td>\n   <td style=\"text-align:right;\"> 122620 </td>\n   <td style=\"text-align:right;\"> 92.1 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> 12-CPR_1_ID_14_ </td>\n   <td style=\"text-align:right;\"> 154920 </td>\n   <td style=\"text-align:right;\"> 82372 </td>\n   <td style=\"text-align:right;\"> 81798 </td>\n   <td style=\"text-align:right;\"> 52.8 </td>\n   <td style=\"text-align:right;\"> 127207 </td>\n   <td style=\"text-align:right;\"> 123701 </td>\n   <td style=\"text-align:right;\"> 117516 </td>\n   <td style=\"text-align:right;\"> 92.4 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> 13-CPR_1_ID_15_ </td>\n   <td style=\"text-align:right;\"> 165533 </td>\n   <td style=\"text-align:right;\"> 100962 </td>\n   <td style=\"text-align:right;\"> 98756 </td>\n   <td style=\"text-align:right;\"> 59.7 </td>\n   <td style=\"text-align:right;\"> 181637 </td>\n   <td style=\"text-align:right;\"> 174765 </td>\n   <td style=\"text-align:right;\"> 167385 </td>\n   <td style=\"text-align:right;\"> 92.2 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> 14-CPR_1_ID_16_ </td>\n   <td style=\"text-align:right;\"> 174055 </td>\n   <td style=\"text-align:right;\"> 154970 </td>\n   <td style=\"text-align:right;\"> 153105 </td>\n   <td style=\"text-align:right;\"> 88.0 </td>\n   <td style=\"text-align:right;\"> 137952 </td>\n   <td style=\"text-align:right;\"> 131771 </td>\n   <td style=\"text-align:right;\"> 126534 </td>\n   <td style=\"text-align:right;\"> 91.7 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> 15-CPR_1_ID_18_ </td>\n   <td style=\"text-align:right;\"> 187464 </td>\n   <td style=\"text-align:right;\"> 141613 </td>\n   <td style=\"text-align:right;\"> 136443 </td>\n   <td style=\"text-align:right;\"> 72.8 </td>\n   <td style=\"text-align:right;\"> 119723 </td>\n   <td style=\"text-align:right;\"> 113684 </td>\n   <td style=\"text-align:right;\"> 109776 </td>\n   <td style=\"text-align:right;\"> 91.7 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> 16-CPR_1_ID_19_ </td>\n   <td style=\"text-align:right;\"> 199073 </td>\n   <td style=\"text-align:right;\"> 165283 </td>\n   <td style=\"text-align:right;\"> 163680 </td>\n   <td style=\"text-align:right;\"> 82.2 </td>\n   <td style=\"text-align:right;\"> 57654 </td>\n   <td style=\"text-align:right;\"> 55146 </td>\n   <td style=\"text-align:right;\"> 51706 </td>\n   <td style=\"text-align:right;\"> 89.7 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> 17-CPR_1_ID_20_ </td>\n   <td style=\"text-align:right;\"> 121858 </td>\n   <td style=\"text-align:right;\"> 107172 </td>\n   <td style=\"text-align:right;\"> 105402 </td>\n   <td style=\"text-align:right;\"> 86.5 </td>\n   <td style=\"text-align:right;\"> 70524 </td>\n   <td style=\"text-align:right;\"> 67331 </td>\n   <td style=\"text-align:right;\"> 64356 </td>\n   <td style=\"text-align:right;\"> 91.3 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> 18-CPR_1_ID_21_ </td>\n   <td style=\"text-align:right;\"> 150714 </td>\n   <td style=\"text-align:right;\"> 142004 </td>\n   <td style=\"text-align:right;\"> 140604 </td>\n   <td style=\"text-align:right;\"> 93.3 </td>\n   <td style=\"text-align:right;\"> 207441 </td>\n   <td style=\"text-align:right;\"> 199025 </td>\n   <td style=\"text-align:right;\"> 193426 </td>\n   <td style=\"text-align:right;\"> 93.2 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> 19-CPR_1_ID_22_ </td>\n   <td style=\"text-align:right;\"> 121155 </td>\n   <td style=\"text-align:right;\"> 98484 </td>\n   <td style=\"text-align:right;\"> 96981 </td>\n   <td style=\"text-align:right;\"> 80.0 </td>\n   <td style=\"text-align:right;\"> 174619 </td>\n   <td style=\"text-align:right;\"> 168282 </td>\n   <td style=\"text-align:right;\"> 162395 </td>\n   <td style=\"text-align:right;\"> 93.0 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> 20-CPR_1_ID_23_ </td>\n   <td style=\"text-align:right;\"> 80435 </td>\n   <td style=\"text-align:right;\"> 66396 </td>\n   <td style=\"text-align:right;\"> 65169 </td>\n   <td style=\"text-align:right;\"> 81.0 </td>\n   <td style=\"text-align:right;\"> 119162 </td>\n   <td style=\"text-align:right;\"> 113276 </td>\n   <td style=\"text-align:right;\"> 109138 </td>\n   <td style=\"text-align:right;\"> 91.6 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> 21-CPR_1_ID_24_ </td>\n   <td style=\"text-align:right;\"> 104984 </td>\n   <td style=\"text-align:right;\"> 92580 </td>\n   <td style=\"text-align:right;\"> 90811 </td>\n   <td style=\"text-align:right;\"> 86.5 </td>\n   <td style=\"text-align:right;\"> 185903 </td>\n   <td style=\"text-align:right;\"> 179594 </td>\n   <td style=\"text-align:right;\"> 173934 </td>\n   <td style=\"text-align:right;\"> 93.6 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> 22-CPR_1_ID_26_ </td>\n   <td style=\"text-align:right;\"> 236346 </td>\n   <td style=\"text-align:right;\"> 191192 </td>\n   <td style=\"text-align:right;\"> 188534 </td>\n   <td style=\"text-align:right;\"> 79.8 </td>\n   <td style=\"text-align:right;\"> 202369 </td>\n   <td style=\"text-align:right;\"> 196976 </td>\n   <td style=\"text-align:right;\"> 190007 </td>\n   <td style=\"text-align:right;\"> 93.9 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> 23-CPR_1_ID_27_ </td>\n   <td style=\"text-align:right;\"> 156485 </td>\n   <td style=\"text-align:right;\"> 137223 </td>\n   <td style=\"text-align:right;\"> 134112 </td>\n   <td style=\"text-align:right;\"> 85.7 </td>\n   <td style=\"text-align:right;\"> 101725 </td>\n   <td style=\"text-align:right;\"> 97126 </td>\n   <td style=\"text-align:right;\"> 92636 </td>\n   <td style=\"text-align:right;\"> 91.1 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> 24-CPR_1_ID_28_ </td>\n   <td style=\"text-align:right;\"> 127353 </td>\n   <td style=\"text-align:right;\"> 111643 </td>\n   <td style=\"text-align:right;\"> 109821 </td>\n   <td style=\"text-align:right;\"> 86.2 </td>\n   <td style=\"text-align:right;\"> 170221 </td>\n   <td style=\"text-align:right;\"> 162524 </td>\n   <td style=\"text-align:right;\"> 155675 </td>\n   <td style=\"text-align:right;\"> 91.5 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> 25-CPR_1_ID_29_ </td>\n   <td style=\"text-align:right;\"> 132416 </td>\n   <td style=\"text-align:right;\"> 116805 </td>\n   <td style=\"text-align:right;\"> 115151 </td>\n   <td style=\"text-align:right;\"> 87.0 </td>\n   <td style=\"text-align:right;\"> 139384 </td>\n   <td style=\"text-align:right;\"> 134544 </td>\n   <td style=\"text-align:right;\"> 127957 </td>\n   <td style=\"text-align:right;\"> 91.8 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> 26-CPR_1_ID_30_ </td>\n   <td style=\"text-align:right;\"> 172100 </td>\n   <td style=\"text-align:right;\"> 162217 </td>\n   <td style=\"text-align:right;\"> 160855 </td>\n   <td style=\"text-align:right;\"> 93.5 </td>\n   <td style=\"text-align:right;\"> 112727 </td>\n   <td style=\"text-align:right;\"> 107640 </td>\n   <td style=\"text-align:right;\"> 104009 </td>\n   <td style=\"text-align:right;\"> 92.3 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> 27-CPR_1_ID_31_ </td>\n   <td style=\"text-align:right;\"> 178342 </td>\n   <td style=\"text-align:right;\"> 167885 </td>\n   <td style=\"text-align:right;\"> 165400 </td>\n   <td style=\"text-align:right;\"> 92.7 </td>\n   <td style=\"text-align:right;\"> 119777 </td>\n   <td style=\"text-align:right;\"> 114101 </td>\n   <td style=\"text-align:right;\"> 108237 </td>\n   <td style=\"text-align:right;\"> 90.4 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> 28-CPR_1_ID_32_ </td>\n   <td style=\"text-align:right;\"> 183002 </td>\n   <td style=\"text-align:right;\"> 172658 </td>\n   <td style=\"text-align:right;\"> 170208 </td>\n   <td style=\"text-align:right;\"> 93.0 </td>\n   <td style=\"text-align:right;\"> 163244 </td>\n   <td style=\"text-align:right;\"> 156129 </td>\n   <td style=\"text-align:right;\"> 151718 </td>\n   <td style=\"text-align:right;\"> 92.9 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> 29-CPR_1_ID_34_ </td>\n   <td style=\"text-align:right;\"> 158952 </td>\n   <td style=\"text-align:right;\"> 143494 </td>\n   <td style=\"text-align:right;\"> 141092 </td>\n   <td style=\"text-align:right;\"> 88.8 </td>\n   <td style=\"text-align:right;\"> 136586 </td>\n   <td style=\"text-align:right;\"> 128685 </td>\n   <td style=\"text-align:right;\"> 124018 </td>\n   <td style=\"text-align:right;\"> 90.8 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> 30-CPR_2_ID_1_ </td>\n   <td style=\"text-align:right;\"> 194720 </td>\n   <td style=\"text-align:right;\"> 169302 </td>\n   <td style=\"text-align:right;\"> 166858 </td>\n   <td style=\"text-align:right;\"> 85.7 </td>\n   <td style=\"text-align:right;\"> 139205 </td>\n   <td style=\"text-align:right;\"> 135316 </td>\n   <td style=\"text-align:right;\"> 129682 </td>\n   <td style=\"text-align:right;\"> 93.2 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> 31-CPR_2_ID_3_ </td>\n   <td style=\"text-align:right;\"> 194060 </td>\n   <td style=\"text-align:right;\"> 171082 </td>\n   <td style=\"text-align:right;\"> 168250 </td>\n   <td style=\"text-align:right;\"> 86.7 </td>\n   <td style=\"text-align:right;\"> 212589 </td>\n   <td style=\"text-align:right;\"> 206838 </td>\n   <td style=\"text-align:right;\"> 198641 </td>\n   <td style=\"text-align:right;\"> 93.4 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> 32-CPR_2_ID_4_ </td>\n   <td style=\"text-align:right;\"> 179081 </td>\n   <td style=\"text-align:right;\"> 148520 </td>\n   <td style=\"text-align:right;\"> 145983 </td>\n   <td style=\"text-align:right;\"> 81.5 </td>\n   <td style=\"text-align:right;\"> 53088 </td>\n   <td style=\"text-align:right;\"> 51392 </td>\n   <td style=\"text-align:right;\"> 48520 </td>\n   <td style=\"text-align:right;\"> 91.4 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> 33-CPR_2_ID_5_ </td>\n   <td style=\"text-align:right;\"> 166777 </td>\n   <td style=\"text-align:right;\"> 142691 </td>\n   <td style=\"text-align:right;\"> 140932 </td>\n   <td style=\"text-align:right;\"> 84.5 </td>\n   <td style=\"text-align:right;\"> 237970 </td>\n   <td style=\"text-align:right;\"> 219557 </td>\n   <td style=\"text-align:right;\"> 206262 </td>\n   <td style=\"text-align:right;\"> 86.7 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> 34-CPR_2_ID_6_ </td>\n   <td style=\"text-align:right;\"> 149638 </td>\n   <td style=\"text-align:right;\"> 132537 </td>\n   <td style=\"text-align:right;\"> 130439 </td>\n   <td style=\"text-align:right;\"> 87.2 </td>\n   <td style=\"text-align:right;\"> 77732 </td>\n   <td style=\"text-align:right;\"> 75401 </td>\n   <td style=\"text-align:right;\"> 71710 </td>\n   <td style=\"text-align:right;\"> 92.3 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> 35-CPR_2_ID_7_ </td>\n   <td style=\"text-align:right;\"> 174663 </td>\n   <td style=\"text-align:right;\"> 145714 </td>\n   <td style=\"text-align:right;\"> 143138 </td>\n   <td style=\"text-align:right;\"> 82.0 </td>\n   <td style=\"text-align:right;\"> 81727 </td>\n   <td style=\"text-align:right;\"> 79459 </td>\n   <td style=\"text-align:right;\"> 75761 </td>\n   <td style=\"text-align:right;\"> 92.7 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> 36-CPR_2_ID_9_ </td>\n   <td style=\"text-align:right;\"> 171703 </td>\n   <td style=\"text-align:right;\"> 141792 </td>\n   <td style=\"text-align:right;\"> 139921 </td>\n   <td style=\"text-align:right;\"> 81.5 </td>\n   <td style=\"text-align:right;\"> 207408 </td>\n   <td style=\"text-align:right;\"> 202506 </td>\n   <td style=\"text-align:right;\"> 195469 </td>\n   <td style=\"text-align:right;\"> 94.2 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> 37-CPR_2_ID_10_ </td>\n   <td style=\"text-align:right;\"> 153543 </td>\n   <td style=\"text-align:right;\"> 137488 </td>\n   <td style=\"text-align:right;\"> 134897 </td>\n   <td style=\"text-align:right;\"> 87.9 </td>\n   <td style=\"text-align:right;\"> 144427 </td>\n   <td style=\"text-align:right;\"> 141116 </td>\n   <td style=\"text-align:right;\"> 135198 </td>\n   <td style=\"text-align:right;\"> 93.6 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> 38-CPR_2_ID_11_ </td>\n   <td style=\"text-align:right;\"> 180363 </td>\n   <td style=\"text-align:right;\"> 152422 </td>\n   <td style=\"text-align:right;\"> 150795 </td>\n   <td style=\"text-align:right;\"> 83.6 </td>\n   <td style=\"text-align:right;\"> 221320 </td>\n   <td style=\"text-align:right;\"> 215203 </td>\n   <td style=\"text-align:right;\"> 207024 </td>\n   <td style=\"text-align:right;\"> 93.5 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> 39-CPR_2_ID_12_ </td>\n   <td style=\"text-align:right;\"> 150636 </td>\n   <td style=\"text-align:right;\"> 122151 </td>\n   <td style=\"text-align:right;\"> 120213 </td>\n   <td style=\"text-align:right;\"> 79.8 </td>\n   <td style=\"text-align:right;\"> 365807 </td>\n   <td style=\"text-align:right;\"> 355825 </td>\n   <td style=\"text-align:right;\"> 342978 </td>\n   <td style=\"text-align:right;\"> 93.8 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> 40-CPR_2_ID_13_ </td>\n   <td style=\"text-align:right;\"> 194784 </td>\n   <td style=\"text-align:right;\"> 180872 </td>\n   <td style=\"text-align:right;\"> 177058 </td>\n   <td style=\"text-align:right;\"> 90.9 </td>\n   <td style=\"text-align:right;\"> 135022 </td>\n   <td style=\"text-align:right;\"> 131227 </td>\n   <td style=\"text-align:right;\"> 124090 </td>\n   <td style=\"text-align:right;\"> 91.9 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> 41-CPR_2_ID_15_ </td>\n   <td style=\"text-align:right;\"> 197928 </td>\n   <td style=\"text-align:right;\"> 174280 </td>\n   <td style=\"text-align:right;\"> 172050 </td>\n   <td style=\"text-align:right;\"> 86.9 </td>\n   <td style=\"text-align:right;\"> 193553 </td>\n   <td style=\"text-align:right;\"> 188006 </td>\n   <td style=\"text-align:right;\"> 180216 </td>\n   <td style=\"text-align:right;\"> 93.1 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> 42-CPR_2_ID_16_ </td>\n   <td style=\"text-align:right;\"> 188135 </td>\n   <td style=\"text-align:right;\"> 175790 </td>\n   <td style=\"text-align:right;\"> 174228 </td>\n   <td style=\"text-align:right;\"> 92.6 </td>\n   <td style=\"text-align:right;\"> 147285 </td>\n   <td style=\"text-align:right;\"> 143187 </td>\n   <td style=\"text-align:right;\"> 137576 </td>\n   <td style=\"text-align:right;\"> 93.4 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> 43-CPR_2_ID_17_ </td>\n   <td style=\"text-align:right;\"> 174942 </td>\n   <td style=\"text-align:right;\"> 145002 </td>\n   <td style=\"text-align:right;\"> 142740 </td>\n   <td style=\"text-align:right;\"> 81.6 </td>\n   <td style=\"text-align:right;\"> 174113 </td>\n   <td style=\"text-align:right;\"> 170004 </td>\n   <td style=\"text-align:right;\"> 163659 </td>\n   <td style=\"text-align:right;\"> 94.0 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> 44-CPR_2_ID_18_ </td>\n   <td style=\"text-align:right;\"> 153984 </td>\n   <td style=\"text-align:right;\"> 135955 </td>\n   <td style=\"text-align:right;\"> 134263 </td>\n   <td style=\"text-align:right;\"> 87.2 </td>\n   <td style=\"text-align:right;\"> 131276 </td>\n   <td style=\"text-align:right;\"> 127604 </td>\n   <td style=\"text-align:right;\"> 122426 </td>\n   <td style=\"text-align:right;\"> 93.3 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> 45-CPR_2_ID_19_ </td>\n   <td style=\"text-align:right;\"> 194789 </td>\n   <td style=\"text-align:right;\"> 161953 </td>\n   <td style=\"text-align:right;\"> 158427 </td>\n   <td style=\"text-align:right;\"> 81.3 </td>\n   <td style=\"text-align:right;\"> 128156 </td>\n   <td style=\"text-align:right;\"> 124223 </td>\n   <td style=\"text-align:right;\"> 117511 </td>\n   <td style=\"text-align:right;\"> 91.7 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> 46-CPR_2_ID_21_ </td>\n   <td style=\"text-align:right;\"> 194608 </td>\n   <td style=\"text-align:right;\"> 174043 </td>\n   <td style=\"text-align:right;\"> 171831 </td>\n   <td style=\"text-align:right;\"> 88.3 </td>\n   <td style=\"text-align:right;\"> 160623 </td>\n   <td style=\"text-align:right;\"> 156266 </td>\n   <td style=\"text-align:right;\"> 149656 </td>\n   <td style=\"text-align:right;\"> 93.2 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> 47-CPR_2_ID_22_ </td>\n   <td style=\"text-align:right;\"> 160941 </td>\n   <td style=\"text-align:right;\"> 131068 </td>\n   <td style=\"text-align:right;\"> 128824 </td>\n   <td style=\"text-align:right;\"> 80.0 </td>\n   <td style=\"text-align:right;\"> 183353 </td>\n   <td style=\"text-align:right;\"> 178208 </td>\n   <td style=\"text-align:right;\"> 171636 </td>\n   <td style=\"text-align:right;\"> 93.6 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> 48-CPR_2_ID_23_ </td>\n   <td style=\"text-align:right;\"> 165931 </td>\n   <td style=\"text-align:right;\"> 148535 </td>\n   <td style=\"text-align:right;\"> 146897 </td>\n   <td style=\"text-align:right;\"> 88.5 </td>\n   <td style=\"text-align:right;\"> 89249 </td>\n   <td style=\"text-align:right;\"> 86797 </td>\n   <td style=\"text-align:right;\"> 83044 </td>\n   <td style=\"text-align:right;\"> 93.0 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> 49-CPR_2_ID_24_ </td>\n   <td style=\"text-align:right;\"> 54433 </td>\n   <td style=\"text-align:right;\"> 50624 </td>\n   <td style=\"text-align:right;\"> 50116 </td>\n   <td style=\"text-align:right;\"> 92.1 </td>\n   <td style=\"text-align:right;\"> 116076 </td>\n   <td style=\"text-align:right;\"> 110431 </td>\n   <td style=\"text-align:right;\"> 104890 </td>\n   <td style=\"text-align:right;\"> 90.4 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> 50-CPR_2_ID_25_ </td>\n   <td style=\"text-align:right;\"> 117781 </td>\n   <td style=\"text-align:right;\"> 101928 </td>\n   <td style=\"text-align:right;\"> 100424 </td>\n   <td style=\"text-align:right;\"> 85.3 </td>\n   <td style=\"text-align:right;\"> 125438 </td>\n   <td style=\"text-align:right;\"> 119556 </td>\n   <td style=\"text-align:right;\"> 113333 </td>\n   <td style=\"text-align:right;\"> 90.3 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> 51-CPR_2_ID_27_ </td>\n   <td style=\"text-align:right;\"> 142756 </td>\n   <td style=\"text-align:right;\"> 107233 </td>\n   <td style=\"text-align:right;\"> 105385 </td>\n   <td style=\"text-align:right;\"> 73.8 </td>\n   <td style=\"text-align:right;\"> 30590 </td>\n   <td style=\"text-align:right;\"> 29864 </td>\n   <td style=\"text-align:right;\"> 27751 </td>\n   <td style=\"text-align:right;\"> 90.7 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> 52-CPR_3_ID_1_ </td>\n   <td style=\"text-align:right;\"> 111133 </td>\n   <td style=\"text-align:right;\"> 85681 </td>\n   <td style=\"text-align:right;\"> 83994 </td>\n   <td style=\"text-align:right;\"> 75.6 </td>\n   <td style=\"text-align:right;\"> 188262 </td>\n   <td style=\"text-align:right;\"> 182359 </td>\n   <td style=\"text-align:right;\"> 174176 </td>\n   <td style=\"text-align:right;\"> 92.5 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> 53-CPR_3_ID_3_ </td>\n   <td style=\"text-align:right;\"> 131736 </td>\n   <td style=\"text-align:right;\"> 110547 </td>\n   <td style=\"text-align:right;\"> 109180 </td>\n   <td style=\"text-align:right;\"> 82.9 </td>\n   <td style=\"text-align:right;\"> 149259 </td>\n   <td style=\"text-align:right;\"> 144930 </td>\n   <td style=\"text-align:right;\"> 138719 </td>\n   <td style=\"text-align:right;\"> 92.9 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> 54-CPR_3_ID_4_ </td>\n   <td style=\"text-align:right;\"> 144501 </td>\n   <td style=\"text-align:right;\"> 127699 </td>\n   <td style=\"text-align:right;\"> 125997 </td>\n   <td style=\"text-align:right;\"> 87.2 </td>\n   <td style=\"text-align:right;\"> 348047 </td>\n   <td style=\"text-align:right;\"> 337956 </td>\n   <td style=\"text-align:right;\"> 325604 </td>\n   <td style=\"text-align:right;\"> 93.6 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> 55-CPR_3_ID_5_ </td>\n   <td style=\"text-align:right;\"> 154373 </td>\n   <td style=\"text-align:right;\"> 138771 </td>\n   <td style=\"text-align:right;\"> 137538 </td>\n   <td style=\"text-align:right;\"> 89.1 </td>\n   <td style=\"text-align:right;\"> 162972 </td>\n   <td style=\"text-align:right;\"> 157261 </td>\n   <td style=\"text-align:right;\"> 151439 </td>\n   <td style=\"text-align:right;\"> 92.9 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> 56-CPR_3_ID_6_ </td>\n   <td style=\"text-align:right;\"> 150617 </td>\n   <td style=\"text-align:right;\"> 135967 </td>\n   <td style=\"text-align:right;\"> 134698 </td>\n   <td style=\"text-align:right;\"> 89.4 </td>\n   <td style=\"text-align:right;\"> 235204 </td>\n   <td style=\"text-align:right;\"> 228457 </td>\n   <td style=\"text-align:right;\"> 220339 </td>\n   <td style=\"text-align:right;\"> 93.7 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> 57-CPR_3_ID_7_ </td>\n   <td style=\"text-align:right;\"> 199644 </td>\n   <td style=\"text-align:right;\"> 184698 </td>\n   <td style=\"text-align:right;\"> 182638 </td>\n   <td style=\"text-align:right;\"> 91.5 </td>\n   <td style=\"text-align:right;\"> 165181 </td>\n   <td style=\"text-align:right;\"> 159075 </td>\n   <td style=\"text-align:right;\"> 150736 </td>\n   <td style=\"text-align:right;\"> 91.3 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> 58-CPR_3_ID_9_ </td>\n   <td style=\"text-align:right;\"> 176030 </td>\n   <td style=\"text-align:right;\"> 161246 </td>\n   <td style=\"text-align:right;\"> 159690 </td>\n   <td style=\"text-align:right;\"> 90.7 </td>\n   <td style=\"text-align:right;\"> 101926 </td>\n   <td style=\"text-align:right;\"> 98194 </td>\n   <td style=\"text-align:right;\"> 93307 </td>\n   <td style=\"text-align:right;\"> 91.5 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> 59-CPR_3_ID_10_ </td>\n   <td style=\"text-align:right;\"> 138047 </td>\n   <td style=\"text-align:right;\"> 128819 </td>\n   <td style=\"text-align:right;\"> 127705 </td>\n   <td style=\"text-align:right;\"> 92.5 </td>\n   <td style=\"text-align:right;\"> 78978 </td>\n   <td style=\"text-align:right;\"> 75907 </td>\n   <td style=\"text-align:right;\"> 72554 </td>\n   <td style=\"text-align:right;\"> 91.9 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> 60-CPR_3_ID_11_ </td>\n   <td style=\"text-align:right;\"> 127549 </td>\n   <td style=\"text-align:right;\"> 111467 </td>\n   <td style=\"text-align:right;\"> 109994 </td>\n   <td style=\"text-align:right;\"> 86.2 </td>\n   <td style=\"text-align:right;\"> 764251 </td>\n   <td style=\"text-align:right;\"> 743533 </td>\n   <td style=\"text-align:right;\"> 713247 </td>\n   <td style=\"text-align:right;\"> 93.3 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> 61-CPR_3_ID_12_ </td>\n   <td style=\"text-align:right;\"> 99488 </td>\n   <td style=\"text-align:right;\"> 89824 </td>\n   <td style=\"text-align:right;\"> 88534 </td>\n   <td style=\"text-align:right;\"> 89.0 </td>\n   <td style=\"text-align:right;\"> 152306 </td>\n   <td style=\"text-align:right;\"> 147417 </td>\n   <td style=\"text-align:right;\"> 141727 </td>\n   <td style=\"text-align:right;\"> 93.1 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> 62-CPR_3_ID_13_ </td>\n   <td style=\"text-align:right;\"> 144619 </td>\n   <td style=\"text-align:right;\"> 129452 </td>\n   <td style=\"text-align:right;\"> 128198 </td>\n   <td style=\"text-align:right;\"> 88.6 </td>\n   <td style=\"text-align:right;\"> 127896 </td>\n   <td style=\"text-align:right;\"> 124206 </td>\n   <td style=\"text-align:right;\"> 119095 </td>\n   <td style=\"text-align:right;\"> 93.1 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> 63-CPR_3_ID_15_ </td>\n   <td style=\"text-align:right;\"> 173235 </td>\n   <td style=\"text-align:right;\"> 144180 </td>\n   <td style=\"text-align:right;\"> 142702 </td>\n   <td style=\"text-align:right;\"> 82.4 </td>\n   <td style=\"text-align:right;\"> 292673 </td>\n   <td style=\"text-align:right;\"> 282276 </td>\n   <td style=\"text-align:right;\"> 271096 </td>\n   <td style=\"text-align:right;\"> 92.6 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> 64-CPR_3_ID_16_ </td>\n   <td style=\"text-align:right;\"> 178289 </td>\n   <td style=\"text-align:right;\"> 143108 </td>\n   <td style=\"text-align:right;\"> 141138 </td>\n   <td style=\"text-align:right;\"> 79.2 </td>\n   <td style=\"text-align:right;\"> 34818 </td>\n   <td style=\"text-align:right;\"> 33694 </td>\n   <td style=\"text-align:right;\"> 31628 </td>\n   <td style=\"text-align:right;\"> 90.8 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> 65-CPR_3_ID_17_ </td>\n   <td style=\"text-align:right;\"> 162707 </td>\n   <td style=\"text-align:right;\"> 126581 </td>\n   <td style=\"text-align:right;\"> 124884 </td>\n   <td style=\"text-align:right;\"> 76.8 </td>\n   <td style=\"text-align:right;\"> 250949 </td>\n   <td style=\"text-align:right;\"> 244820 </td>\n   <td style=\"text-align:right;\"> 234509 </td>\n   <td style=\"text-align:right;\"> 93.4 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> 66-CPR_3_ID_18_ </td>\n   <td style=\"text-align:right;\"> 131876 </td>\n   <td style=\"text-align:right;\"> 106565 </td>\n   <td style=\"text-align:right;\"> 104364 </td>\n   <td style=\"text-align:right;\"> 79.1 </td>\n   <td style=\"text-align:right;\"> 110678 </td>\n   <td style=\"text-align:right;\"> 108129 </td>\n   <td style=\"text-align:right;\"> 103754 </td>\n   <td style=\"text-align:right;\"> 93.7 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> 67-CPR_3_ID_19_ </td>\n   <td style=\"text-align:right;\"> 128988 </td>\n   <td style=\"text-align:right;\"> 102637 </td>\n   <td style=\"text-align:right;\"> 100914 </td>\n   <td style=\"text-align:right;\"> 78.2 </td>\n   <td style=\"text-align:right;\"> 58035 </td>\n   <td style=\"text-align:right;\"> 56351 </td>\n   <td style=\"text-align:right;\"> 53356 </td>\n   <td style=\"text-align:right;\"> 91.9 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> 68-CPR_3_ID_21_ </td>\n   <td style=\"text-align:right;\"> 107663 </td>\n   <td style=\"text-align:right;\"> 92109 </td>\n   <td style=\"text-align:right;\"> 90482 </td>\n   <td style=\"text-align:right;\"> 84.0 </td>\n   <td style=\"text-align:right;\"> 172563 </td>\n   <td style=\"text-align:right;\"> 165373 </td>\n   <td style=\"text-align:right;\"> 158612 </td>\n   <td style=\"text-align:right;\"> 91.9 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> 69-CPR_3_ID_22_ </td>\n   <td style=\"text-align:right;\"> 112212 </td>\n   <td style=\"text-align:right;\"> 96684 </td>\n   <td style=\"text-align:right;\"> 94953 </td>\n   <td style=\"text-align:right;\"> 84.6 </td>\n   <td style=\"text-align:right;\"> 173570 </td>\n   <td style=\"text-align:right;\"> 168441 </td>\n   <td style=\"text-align:right;\"> 158656 </td>\n   <td style=\"text-align:right;\"> 91.4 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> 70-CPR_3_ID_23_ </td>\n   <td style=\"text-align:right;\"> 132352 </td>\n   <td style=\"text-align:right;\"> 113912 </td>\n   <td style=\"text-align:right;\"> 112257 </td>\n   <td style=\"text-align:right;\"> 84.8 </td>\n   <td style=\"text-align:right;\"> 148617 </td>\n   <td style=\"text-align:right;\"> 143765 </td>\n   <td style=\"text-align:right;\"> 137513 </td>\n   <td style=\"text-align:right;\"> 92.5 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> 71-CPR_3_ID_24_ </td>\n   <td style=\"text-align:right;\"> 196535 </td>\n   <td style=\"text-align:right;\"> 174115 </td>\n   <td style=\"text-align:right;\"> 171928 </td>\n   <td style=\"text-align:right;\"> 87.5 </td>\n   <td style=\"text-align:right;\"> 405832 </td>\n   <td style=\"text-align:right;\"> 395478 </td>\n   <td style=\"text-align:right;\"> 382290 </td>\n   <td style=\"text-align:right;\"> 94.2 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> 72-CPR_4_ID_1_ </td>\n   <td style=\"text-align:right;\"> 196923 </td>\n   <td style=\"text-align:right;\"> 166713 </td>\n   <td style=\"text-align:right;\"> 164208 </td>\n   <td style=\"text-align:right;\"> 83.4 </td>\n   <td style=\"text-align:right;\"> 35382 </td>\n   <td style=\"text-align:right;\"> 33909 </td>\n   <td style=\"text-align:right;\"> 31733 </td>\n   <td style=\"text-align:right;\"> 89.7 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> 73-CPR_4_ID_3_ </td>\n   <td style=\"text-align:right;\"> 213738 </td>\n   <td style=\"text-align:right;\"> 175220 </td>\n   <td style=\"text-align:right;\"> 171992 </td>\n   <td style=\"text-align:right;\"> 80.5 </td>\n   <td style=\"text-align:right;\"> 156704 </td>\n   <td style=\"text-align:right;\"> 143311 </td>\n   <td style=\"text-align:right;\"> 131255 </td>\n   <td style=\"text-align:right;\"> 83.8 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> 74-CPR_4_ID_4_ </td>\n   <td style=\"text-align:right;\"> 205473 </td>\n   <td style=\"text-align:right;\"> 178940 </td>\n   <td style=\"text-align:right;\"> 176603 </td>\n   <td style=\"text-align:right;\"> 85.9 </td>\n   <td style=\"text-align:right;\"> 112970 </td>\n   <td style=\"text-align:right;\"> 109524 </td>\n   <td style=\"text-align:right;\"> 103878 </td>\n   <td style=\"text-align:right;\"> 92.0 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> 75-CPR_4_ID_5_ </td>\n   <td style=\"text-align:right;\"> 189932 </td>\n   <td style=\"text-align:right;\"> 165289 </td>\n   <td style=\"text-align:right;\"> 163135 </td>\n   <td style=\"text-align:right;\"> 85.9 </td>\n   <td style=\"text-align:right;\"> 35141 </td>\n   <td style=\"text-align:right;\"> 33968 </td>\n   <td style=\"text-align:right;\"> 31796 </td>\n   <td style=\"text-align:right;\"> 90.5 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> 76-CPR_4_ID_7_ </td>\n   <td style=\"text-align:right;\"> 197530 </td>\n   <td style=\"text-align:right;\"> 166801 </td>\n   <td style=\"text-align:right;\"> 164410 </td>\n   <td style=\"text-align:right;\"> 83.2 </td>\n   <td style=\"text-align:right;\"> 194218 </td>\n   <td style=\"text-align:right;\"> 185074 </td>\n   <td style=\"text-align:right;\"> 176431 </td>\n   <td style=\"text-align:right;\"> 90.8 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> 77-CPR_4_ID_8_ </td>\n   <td style=\"text-align:right;\"> 235558 </td>\n   <td style=\"text-align:right;\"> 194621 </td>\n   <td style=\"text-align:right;\"> 191317 </td>\n   <td style=\"text-align:right;\"> 81.2 </td>\n   <td style=\"text-align:right;\"> 113842 </td>\n   <td style=\"text-align:right;\"> 110778 </td>\n   <td style=\"text-align:right;\"> 103904 </td>\n   <td style=\"text-align:right;\"> 91.3 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> 78-CPR_4_ID_9_ </td>\n   <td style=\"text-align:right;\"> 230985 </td>\n   <td style=\"text-align:right;\"> 193352 </td>\n   <td style=\"text-align:right;\"> 189591 </td>\n   <td style=\"text-align:right;\"> 82.1 </td>\n   <td style=\"text-align:right;\"> 176304 </td>\n   <td style=\"text-align:right;\"> 168346 </td>\n   <td style=\"text-align:right;\"> 160614 </td>\n   <td style=\"text-align:right;\"> 91.1 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> 79-CPR_4_ID_11_ </td>\n   <td style=\"text-align:right;\"> 218815 </td>\n   <td style=\"text-align:right;\"> 181431 </td>\n   <td style=\"text-align:right;\"> 177308 </td>\n   <td style=\"text-align:right;\"> 81.0 </td>\n   <td style=\"text-align:right;\"> 98280 </td>\n   <td style=\"text-align:right;\"> 90284 </td>\n   <td style=\"text-align:right;\"> 84739 </td>\n   <td style=\"text-align:right;\"> 86.2 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> 80-CPR_4_ID_12_ </td>\n   <td style=\"text-align:right;\"> 214875 </td>\n   <td style=\"text-align:right;\"> 172492 </td>\n   <td style=\"text-align:right;\"> 168539 </td>\n   <td style=\"text-align:right;\"> 78.4 </td>\n   <td style=\"text-align:right;\"> 43775 </td>\n   <td style=\"text-align:right;\"> 42215 </td>\n   <td style=\"text-align:right;\"> 40632 </td>\n   <td style=\"text-align:right;\"> 92.8 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> 81-CPR_4_ID_13_ </td>\n   <td style=\"text-align:right;\"> 206448 </td>\n   <td style=\"text-align:right;\"> 170783 </td>\n   <td style=\"text-align:right;\"> 162683 </td>\n   <td style=\"text-align:right;\"> 78.8 </td>\n   <td style=\"text-align:right;\"> 343639 </td>\n   <td style=\"text-align:right;\"> 332962 </td>\n   <td style=\"text-align:right;\"> 312529 </td>\n   <td style=\"text-align:right;\"> 90.9 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> 82-CPR_4_ID_15_ </td>\n   <td style=\"text-align:right;\"> 193011 </td>\n   <td style=\"text-align:right;\"> 156690 </td>\n   <td style=\"text-align:right;\"> 150368 </td>\n   <td style=\"text-align:right;\"> 77.9 </td>\n   <td style=\"text-align:right;\"> 262846 </td>\n   <td style=\"text-align:right;\"> 253570 </td>\n   <td style=\"text-align:right;\"> 243480 </td>\n   <td style=\"text-align:right;\"> 92.6 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> 83-CPR_4_ID_16_ </td>\n   <td style=\"text-align:right;\"> 162913 </td>\n   <td style=\"text-align:right;\"> 125167 </td>\n   <td style=\"text-align:right;\"> 122596 </td>\n   <td style=\"text-align:right;\"> 75.3 </td>\n   <td style=\"text-align:right;\"> 11798 </td>\n   <td style=\"text-align:right;\"> 11246 </td>\n   <td style=\"text-align:right;\"> 10326 </td>\n   <td style=\"text-align:right;\"> 87.5 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> 84-CPR_4_ID_17_ </td>\n   <td style=\"text-align:right;\"> 142434 </td>\n   <td style=\"text-align:right;\"> 107027 </td>\n   <td style=\"text-align:right;\"> 105677 </td>\n   <td style=\"text-align:right;\"> 74.2 </td>\n   <td style=\"text-align:right;\"> 102915 </td>\n   <td style=\"text-align:right;\"> 98756 </td>\n   <td style=\"text-align:right;\"> 94552 </td>\n   <td style=\"text-align:right;\"> 91.9 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> 85-CPR_4_ID_19_ </td>\n   <td style=\"text-align:right;\"> 228236 </td>\n   <td style=\"text-align:right;\"> 196262 </td>\n   <td style=\"text-align:right;\"> 193991 </td>\n   <td style=\"text-align:right;\"> 85.0 </td>\n   <td style=\"text-align:right;\"> 185461 </td>\n   <td style=\"text-align:right;\"> 180209 </td>\n   <td style=\"text-align:right;\"> 167045 </td>\n   <td style=\"text-align:right;\"> 90.1 </td>\n  </tr>\n</tbody>\n</table></div>\n\n`````\n:::\n:::\n\n\n::: {.callout-note title=\"Negative Controls\"}\nThe **No-Template Control (NTC)** and **Extraction Blank** samples in the 18S dataset did not pass the initial **DADA2 filtering step**, resulting in zero retained reads after quality filtering.\\\nConsequently, these controls were **excluded from downstream analysis** (denoising, merging, and taxonomy assignment).\n\nTheir exclusion is consistent with expectations for negative controls, indicating the absence of detectable contamination above sequencing background levels.\n:::\n\n::: {.callout-note}\n### 💬 Discussion — reads retained\n\nThe proportion of reads that were kept following the DADA2 pipeline is good: **84%** and **91%** for **18S** and **COI**, respectively. This leaves an average of **136K** and **142K** reads for **18S** and **COI**, respectively.\nLet's note that for 18S, samples 12 and 13 lost more then the rest: **53%** and **60%**, respectively.\n:::\n\n# 18S Dataset\n\n## 📦 Build the phyloseq object (18S)\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(phyloseq)\n\n# ---- paths ----\ndatadir <- \"data/18S\"\n\n# ---- load DADA2 outputs ----\nseqtab.nochim <- readRDS(file.path(datadir, \"seqtab_nochim.rds\"))\ntaxa          <- readRDS(file.path(datadir, \"taxa.rds\"))\n\n# Make sure taxonomy is a proper matrix and has consistent column names\ntaxa <- as.matrix(taxa)\ntarget_cols <- c(\n  \"Kingdom\",\"Subkingdom_1\",\"Subkingdom_2\",\"Phylum\",\"Subphylum\",\"Subphylum_1\",\"Superclass\",\n  \"Class\",\"Subclass\",\"Infraclass\",\"Superorder\",\"Order\",\"Suborder_1\",\"Suborder_2\",\"Suborder_3\",\n  \"Family\",\"Subfamily\",\"Genus\",\"Subgenus\",\"Species\"\n)\ncolnames(taxa) <- target_cols[seq_len(ncol(taxa))]\n\n# Load metadata\nmetadat <- readRDS(file.path(datadir, \"metadata_18S.rds\")) \n\n# Create a Phyloseq object\n\nrownames(seqtab.nochim) <- sub(\"_$\", \"\", rownames(seqtab.nochim))\n\nps_18s <- phyloseq(otu_table(seqtab.nochim, taxa_are_rows = F), \n               sample_data(metadat), \n               tax_table(taxa))\nsaveRDS(ps_18s, \"data/ps_18s.rds\")\n  \ncat(\"🔹 A summary of the phyloseq object \\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n🔹 A summary of the phyloseq object \n```\n\n\n:::\n\n```{.r .cell-code}\nps_18s\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nphyloseq-class experiment-level object\notu_table()   OTU Table:         [ 5154 taxa and 85 samples ]\nsample_data() Sample Data:       [ 85 samples by 8 sample variables ]\ntax_table()   Taxonomy Table:    [ 5154 taxa by 20 taxonomic ranks ]\n```\n\n\n:::\n\n```{.r .cell-code}\n# storing the ASV sequences and assigning them with a name and then renaming the taxa object\ndna <- Biostrings::DNAStringSet(taxa_names(ps_18s))\nnames(dna) <- taxa_names(ps_18s)\nps_18s <- merge_phyloseq(ps_18s, dna)\ntaxa_names(ps_18s) <- paste0(\"ASV\", seq(ntaxa(ps_18s)))\n```\n:::\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n🔹 These are the metadata variables:\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"cpr\"      \"ID\"       \"Sample\"   \"Number\"   \"Inst\"     \"lat\"      \"lon\"     \n[8] \"Position\"\n```\n\n\n:::\n:::\n\n\n### Read depth per sample\n\n::: {.cell}\n\n```{.r .cell-code}\nread_depth <- data.frame(\nSample = sample_names(ps_18s),\nReads = sample_sums(ps_18s),\ncheck.names = FALSE\n)\n\nggplot(read_depth, aes(x = Sample, y = Reads)) +\ngeom_col() +\ntheme_minimal() +\ntheme(axis.text.x = element_text(angle = 45, hjust = 1)) + # Rotate x-axis labels for better readability\nscale_x_discrete(\n    labels = function(x) substr(x, 1, 6), # Show only the first 5 characters of each label\n    breaks = function(x) x[seq(1, length(x), by = 4)] # Show every 4th label\n  ) +\nlabs(\ntitle = \"Sequencing depth per sample\",\nx = \"Sample\",\ny = \"Number of non-chimeric reads\"\n)\n```\n\n::: {.cell-output-display}\n![](Manuscript_analysis_files/figure-html/unnamed-chunk-4-1.png){width=672}\n:::\n:::\n\n\n# COI Dataset\n\n## 📦 Build the phyloseq object (COI)\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(phyloseq)\n\n# ---- paths ----\ndatadir <- \"data/COI\"\n\n# ---- load DADA2 outputs ----\nseqtab.nochim <- readRDS(file.path(datadir, \"seqtab_nochim.rds\"))\ntaxa          <- readRDS(file.path(datadir, \"taxa.rds\"))\n\n# Make sure taxonomy is a proper matrix and has consistent column names\ntaxa <- as.matrix(taxa)\ntarget_cols <- c(\n  \"Kingdom\",\"Subkingdom_1\",\"Subkingdom_2\",\"Phylum\",\"Subphylum\",\"Subphylum_1\",\"Superclass\",\n  \"Class\",\"Subclass\",\"Infraclass\",\"Superorder\",\"Order\",\"Suborder_1\",\"Suborder_2\",\"Suborder_3\",\n  \"Family\",\"Subfamily\",\"Genus\",\"Subgenus\",\"Species\"\n)\ncolnames(taxa) <- target_cols[seq_len(ncol(taxa))]\n\n# Load metadata\nmetadat <- readRDS(file.path(datadir, \"metadata_COI.rds\")) \n\n# Create a Phyloseq object\n\nrownames(seqtab.nochim) <- sub(\"_$\", \"\", rownames(seqtab.nochim))\n\nps_coi <- phyloseq(otu_table(seqtab.nochim, taxa_are_rows = F), \n               sample_data(metadat), \n               tax_table(taxa))\n\nsaveRDS(ps_coi, \"data/ps_coi.rds\")\ncat(\"🔹 ** A summary of the phyloseq object**\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n🔹 ** A summary of the phyloseq object**\n```\n\n\n:::\n\n```{.r .cell-code}\nps_coi\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nphyloseq-class experiment-level object\notu_table()   OTU Table:         [ 18037 taxa and 85 samples ]\nsample_data() Sample Data:       [ 85 samples by 8 sample variables ]\ntax_table()   Taxonomy Table:    [ 18037 taxa by 20 taxonomic ranks ]\n```\n\n\n:::\n\n```{.r .cell-code}\n# storing the ASV sequences and assigning them with a name and then renaming the taxa object\ndna <- Biostrings::DNAStringSet(taxa_names(ps_coi))\nnames(dna) <- taxa_names(ps_coi)\nps_coi <- merge_phyloseq(ps_coi, dna)\ntaxa_names(ps_coi) <- paste0(\"ASV\", seq(ntaxa(ps_coi)))\n```\n:::\n\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n🔹 **These are the metadata variables:**\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"cpr\"      \"ID\"       \"Sample\"   \"Number\"   \"Inst\"     \"lat\"      \"lon\"     \n[8] \"Position\"\n```\n\n\n:::\n:::\n\n\n### Read depth per sample\n\n::: {.cell}\n::: {.cell-output-display}\n![](Manuscript_analysis_files/figure-html/unnamed-chunk-7-1.png){width=672}\n:::\n:::\n\n\n# CPR Dataset\n\n## 📦 Build the phyloseq object (CPR data)\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(phyloseq)\n\n# ---- load data ----\ncounts <- read_csv(\"data/count_table_CPR.csv\")\ntaxo <- read_csv(\"data/taxonomy_table_CPR.csv\")\nmeta <- read_csv(\"data/metadata_CPR.csv\")\n\ntaxtab <- as.matrix(taxo)\nrow.names(taxtab) <- taxo[[8]]\n\n# Create a Phyloseq object\n\nps_cpr <- phyloseq(otu_table(counts, taxa_are_rows = F), \n                   sample_data(meta), \n                   tax_table(taxtab))\nsaveRDS(ps_cpr, \"data/ps_cpr.rds\")\ncat(\"🔹 ** A summary of the phyloseq object**\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n🔹 ** A summary of the phyloseq object**\n```\n\n\n:::\n\n```{.r .cell-code}\nprint(ps_cpr)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nphyloseq-class experiment-level object\notu_table()   OTU Table:         [ 183 taxa and 36 samples ]\nsample_data() Sample Data:       [ 36 samples by 10 sample variables ]\ntax_table()   Taxonomy Table:    [ 183 taxa by 8 taxonomic ranks ]\n```\n\n\n:::\n:::\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n🔹 **These are the metadata variables:**\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n [1] \"Latitude\"            \"Longitude\"           \"Midpoint_Date_Local\"\n [4] \"Year\"                \"Month\"               \"Chlorophyll_Index\"  \n [7] \"Number\"              \"cpr\"                 \"Inst\"               \n[10] \"Position\"           \n```\n\n\n:::\n:::\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n🔹 **These are the taxonomic levels:**\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"Kingdom\"  \"Phylum\"   \"Class\"    \"Order\"    \"Family\"   \"Genus\"    \"Species\" \n[8] \"Organism\"\n```\n\n\n:::\n:::\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n🔹 **These are the metadata variables:**\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n [1] \"Latitude\"            \"Longitude\"           \"Midpoint_Date_Local\"\n [4] \"Year\"                \"Month\"               \"Chlorophyll_Index\"  \n [7] \"Number\"              \"cpr\"                 \"Inst\"               \n[10] \"Position\"           \n```\n\n\n:::\n:::\n\n\n### Counts per sample\n\n::: {.cell}\n::: {.cell-output-display}\n![](Manuscript_analysis_files/figure-html/unnamed-chunk-12-1.png){width=672}\n:::\n:::\n\n\n# Merging datasets\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\nphyloseq-class experiment-level object\notu_table()   OTU Table:         [ 23191 taxa and 85 samples ]\nsample_data() Sample Data:       [ 85 samples by 8 sample variables ]\ntax_table()   Taxonomy Table:    [ 23191 taxa by 21 taxonomic ranks ]\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n  18S   COI \n 5154 18037 \n```\n\n\n:::\n:::\n\n\n### compare presence/absence in eDNA vs CPR\n\n\n::: {.cell}\n::: {.cell-output-display}\n`````{=html}\n<table class=\"table\" style=\"width: auto !important; margin-left: auto; margin-right: auto;\">\n<caption>Taxonomic overlap between eDNA and CPR datasets (presence/absence).</caption>\n <thead>\n  <tr>\n   <th style=\"text-align:left;\"> rank </th>\n   <th style=\"text-align:right;\"> n_edna </th>\n   <th style=\"text-align:right;\"> n_cpr </th>\n   <th style=\"text-align:right;\"> n_shared </th>\n   <th style=\"text-align:right;\"> perc_shared_edna </th>\n   <th style=\"text-align:right;\"> perc_shared_cpr </th>\n  </tr>\n </thead>\n<tbody>\n  <tr>\n   <td style=\"text-align:left;\"> Kingdom </td>\n   <td style=\"text-align:right;\"> 4 </td>\n   <td style=\"text-align:right;\"> 6 </td>\n   <td style=\"text-align:right;\"> 2 </td>\n   <td style=\"text-align:right;\"> 50.0 </td>\n   <td style=\"text-align:right;\"> 33.3 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> Phylum </td>\n   <td style=\"text-align:right;\"> 32 </td>\n   <td style=\"text-align:right;\"> 17 </td>\n   <td style=\"text-align:right;\"> 13 </td>\n   <td style=\"text-align:right;\"> 40.6 </td>\n   <td style=\"text-align:right;\"> 76.5 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> Class </td>\n   <td style=\"text-align:right;\"> 82 </td>\n   <td style=\"text-align:right;\"> 25 </td>\n   <td style=\"text-align:right;\"> 17 </td>\n   <td style=\"text-align:right;\"> 20.7 </td>\n   <td style=\"text-align:right;\"> 68.0 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> Order </td>\n   <td style=\"text-align:right;\"> 189 </td>\n   <td style=\"text-align:right;\"> 44 </td>\n   <td style=\"text-align:right;\"> 22 </td>\n   <td style=\"text-align:right;\"> 11.6 </td>\n   <td style=\"text-align:right;\"> 50.0 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> Family </td>\n   <td style=\"text-align:right;\"> 288 </td>\n   <td style=\"text-align:right;\"> 65 </td>\n   <td style=\"text-align:right;\"> 32 </td>\n   <td style=\"text-align:right;\"> 11.1 </td>\n   <td style=\"text-align:right;\"> 49.2 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> Genus </td>\n   <td style=\"text-align:right;\"> 366 </td>\n   <td style=\"text-align:right;\"> 89 </td>\n   <td style=\"text-align:right;\"> 40 </td>\n   <td style=\"text-align:right;\"> 10.9 </td>\n   <td style=\"text-align:right;\"> 44.9 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> Species </td>\n   <td style=\"text-align:right;\"> 447 </td>\n   <td style=\"text-align:right;\"> 80 </td>\n   <td style=\"text-align:right;\"> 0 </td>\n   <td style=\"text-align:right;\"> 0.0 </td>\n   <td style=\"text-align:right;\"> 0.0 </td>\n  </tr>\n</tbody>\n</table>\n\n`````\n:::\n:::\n\n\n### Combined figures\n\n#### zooplankton\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# ---- genera to plot ----\ngenera10 <- c(\n  \"Paracalanus\",\"Clausocalanus\",\"Nannocalanus\",\"Centropages\",\"Acartia\",\n  \"Calanus\",\"Temora\",\"Metridia\",\"Oithona\",\"Oncaea\"\n)\n\n# ---- palette + named colours for the 10 genera ----\nmy_colors <- c(\"#FF6666\", \"#8DD3C7\", \"#377EB8\", \"#4DAF4A\",\n               \"#984EA3\", \"#A6D854\", \"#FFFF33\", \"#FF7F00\",\n               \"#F781BF\", \"#999999\")\n\ngenus_cols <- setNames(my_colors[1:length(genera10)], genera10)\n\n# ---- helper: phyloseq -> long df with longitude + Genus + PA ----\nps_to_long_df <- function(ps_obj, approach_name, genera_keep, lon_var = NULL, tax_rank = \"Genus\") {\n  stopifnot(inherits(ps_obj, \"phyloseq\"))\n\n  otu <- as(otu_table(ps_obj), \"matrix\")\n  if (!taxa_are_rows(ps_obj)) otu <- t(otu)\n  otu <- (otu > 0) * 1\n\n  tax <- as(tax_table(ps_obj), \"matrix\") %>% as.data.frame(check.names = FALSE)\n  tax$.taxa_id <- rownames(tax)\n\n  sam <- as(sample_data(ps_obj), \"data.frame\") %>%\n    rownames_to_column(\"SampleID\")\n  names(sam) <- trimws(names(sam))\n\n  if (is.null(lon_var)) {\n    lon_candidates <- names(sam)[grepl(\"^lon(gitude)?$\", tolower(names(sam)))]\n    if (length(lon_candidates) == 0) lon_candidates <- names(sam)[grepl(\"lon|long\", tolower(names(sam)))]\n    if (length(lon_candidates) == 0) {\n      stop(\n        \"Could not find a longitude column in sample_data(ps_obj).\\n\",\n        \"Available columns:\\n  \", paste(names(sam), collapse = \", \")\n      )\n    }\n    lon_var <- lon_candidates[1]\n  } else {\n    if (!lon_var %in% names(sam)) {\n      stop(sprintf(\n        \"Longitude column '%s' not found. Available columns:\\n  %s\",\n        lon_var, paste(names(sam), collapse = \", \")\n      ))\n    }\n  }\n\n  if (!tax_rank %in% names(tax)) {\n    stop(sprintf(\"Tax table column '%s' not found. Available tax ranks:\\n  %s\",\n                 tax_rank, paste(names(tax), collapse = \", \")))\n  }\n\n  otu_long <- as.data.frame(otu) %>%\n    rownames_to_column(\".taxa_id\") %>%\n    pivot_longer(cols = -\".taxa_id\", names_to = \"SampleID\", values_to = \"pa\")\n\n  otu_long %>%\n    left_join(tax, by = \".taxa_id\") %>%\n    left_join(sam, by = \"SampleID\") %>%\n    mutate(\n      Genus = as.character(.data[[tax_rank]]),\n      approach = approach_name,\n      longitude = as.numeric(.data[[lon_var]])\n    ) %>%\n    filter(!is.na(Genus), Genus %in% genera_keep) %>%\n    select(approach, SampleID, longitude, Genus, pa)\n}\n\n# ---- transect binning settings ----\nlon_min <- -16.149\nlon_max <- -1.246\nn_bins  <- 10\nlon_breaks <- seq(lon_min, lon_max, length.out = n_bins + 1)\n\n# ---- build binned presence/absence by genus (any detection in bin = present) ----\ndf_binned <- bind_rows(\n  ps_to_long_df(ps_cpr_pa,  \"CPR\",  genera10, lon_var = NULL, tax_rank = \"Genus\"),\n  ps_to_long_df(ps_edna_pa, \"eDNA\", genera10, lon_var = NULL, tax_rank = \"Genus\")\n) %>%\n  filter(!is.na(longitude), longitude >= lon_min, longitude <= lon_max) %>%\n  mutate(lon_bin = cut(longitude, breaks = lon_breaks, include.lowest = TRUE, right = TRUE)) %>%\n  group_by(approach, lon_bin, Genus) %>%\n  summarise(pa = as.integer(any(pa == 1)), .groups = \"drop\") %>%\n  mutate(\n    approach = factor(approach, levels = c(\"CPR\", \"eDNA\"))\n  )\n\n# ---- rank genera by prevalence (most present across bins+approaches = top) ----\ngenus_rank <- df_binned %>%\n  group_by(Genus) %>%\n  summarise(prevalence = sum(pa == 1, na.rm = TRUE), .groups = \"drop\") %>%\n  arrange(desc(prevalence), Genus)\n\ngenus_levels <- genus_rank$Genus\n\n# apply ordering + fill mapping\ndf_binned <- df_binned %>%\n  mutate(\n    Genus = factor(Genus, levels = genus_levels),\n    fill_genus = ifelse(pa == 1, as.character(Genus), NA)\n  )\n\n# reorder colours to match ranked genera\ngenus_cols_ranked <- genus_cols[genus_levels]\n\n# ---- x-axis labels: bin midpoints ----\nbin_mids <- (lon_breaks[-1] + lon_breaks[-length(lon_breaks)]) / 2\nmid_labels <- sprintf(\"%.2f\", bin_mids)\nnames(mid_labels) <- levels(df_binned$lon_bin)\n\n# ---- plot (match phytoplankton style) ----\np <- ggplot(df_binned, aes(x = lon_bin, y = Genus, fill = fill_genus)) +\n  geom_tile(width = 0.95, height = 0.9, colour = \"grey80\") +\n  facet_wrap(~ approach, ncol = 1) +\n  scale_fill_manual(\n    values = genus_cols_ranked,\n    na.value = \"white\",\n    breaks = genus_levels,\n    limits = genus_levels,\n    drop = FALSE,\n    name = \"Genus\"\n  ) +\n  scale_x_discrete(labels = mid_labels) +\n  scale_y_discrete(limits = rev(genus_levels)) +  # most prevalent at TOP\n  labs(x = \"Longitude section (bin midpoint)\", y = NULL) +\n  theme_minimal(base_size = 12) +\n  theme(\n    panel.grid = element_blank(),\n    strip.text = element_text(face = \"bold\"),\n    axis.text.x = element_text(angle = 45, hjust = 1),\n    axis.text.y  = element_blank(),\n    axis.ticks.y = element_blank(),\n    axis.title.y = element_blank()\n  )\n\nprint(p)\n```\n\n::: {.cell-output-display}\n![](Manuscript_analysis_files/figure-html/unnamed-chunk-15-1.png){width=672}\n:::\n:::\n\n\n#### Phytoplankton\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# ---- genera to plot ----\nfamilies9 <- c(\n  \"Rhizosoleniaceae\",\n  \"Chaetoceraceae\",\n  \"Ceratiaceae\",\n  \"Coccolithaceae\",\n  \"Dictyochaceae\",\n  \"Leptocylindraceae\",\n  \"Noelaerhabdaceae\",\n  \"Rhabdosphaeraceae\",\n  \"Prorocentraceae\"\n)\n\n# ---- your palette + named colours for the 10 genera ----\nmy_colors <- c(\"#66C2A5\", \"#FC8D62\", \"#8DA0CB\", \"#E78AC3\", \"#FFD92F\",\n               \"#E5C494\", \"#B3B3B3\", \"#A65628\",\"#FFFFB3\", \"#BEBADA\",\n               \"#FB8072\", \"#80B1D3\", \"#FDB462\")\n\nfam_cols <- setNames(my_colors[1:length(families9)], families9)\n\n# ---- helper: phyloseq -> long df with longitude + Family + PA ----\nps_to_long_df <- function(ps_obj, approach_name, families_keep, lon_var = NULL, tax_rank = \"Family\") {\n  stopifnot(inherits(ps_obj, \"phyloseq\"))\n\n  # OTU (taxa x samples) presence/absence\n  otu <- as(otu_table(ps_obj), \"matrix\")\n  if (!taxa_are_rows(ps_obj)) otu <- t(otu)\n  otu <- (otu > 0) * 1\n\n  # taxonomy\n  tax <- as(tax_table(ps_obj), \"matrix\") %>% as.data.frame(check.names = FALSE)\n  tax$.taxa_id <- rownames(tax)\n\n  # sample data\n  sam <- as(sample_data(ps_obj), \"data.frame\") %>%\n    rownames_to_column(\"SampleID\")\n  names(sam) <- trimws(names(sam))\n\n  # detect longitude column if not provided\n  if (is.null(lon_var)) {\n    lon_candidates <- names(sam)[grepl(\"^lon(gitude)?$\", tolower(names(sam)))]\n    if (length(lon_candidates) == 0) lon_candidates <- names(sam)[grepl(\"lon|long\", tolower(names(sam)))]\n    if (length(lon_candidates) == 0) {\n      stop(\n        \"Could not find a longitude column in sample_data(ps_obj).\\n\",\n        \"Available columns:\\n  \", paste(names(sam), collapse = \", \")\n      )\n    }\n    lon_var <- lon_candidates[1]\n  } else {\n    if (!lon_var %in% names(sam)) {\n      stop(sprintf(\n        \"Longitude column '%s' not found. Available columns:\\n  %s\",\n        lon_var, paste(names(sam), collapse = \", \")\n      ))\n    }\n  }\n\n  if (!tax_rank %in% names(tax)) {\n    stop(sprintf(\"Tax table column '%s' not found. Available tax ranks:\\n  %s\",\n                 tax_rank, paste(names(tax), collapse = \", \")))\n  }\n\n  otu_long <- as.data.frame(otu) %>%\n    rownames_to_column(\".taxa_id\") %>%\n    pivot_longer(cols = -\".taxa_id\", names_to = \"SampleID\", values_to = \"pa\")\n\n  otu_long %>%\n    left_join(tax, by = \".taxa_id\") %>%\n    left_join(sam, by = \"SampleID\") %>%\n    mutate(\n      Family = as.character(.data[[tax_rank]]),\n      approach = approach_name,\n      longitude = as.numeric(.data[[lon_var]])\n    ) %>%\n    filter(!is.na(Family), Family %in% families_keep) %>%\n    select(approach, SampleID, longitude, Family, pa)\n}\n\n# ---- transect binning settings ----\nlon_min <- -16.149\nlon_max <- -1.246\nn_bins  <- 10\nlon_breaks <- seq(lon_min, lon_max, length.out = n_bins + 1)\n\n# ---- build binned presence/absence by family (any detection in bin = present) ----\n# ---- build binned presence/absence by family (any detection in bin = present) ----\ndf_binned <- bind_rows(\n  ps_to_long_df(ps_cpr_pa,  \"CPR\",  families9, lon_var = NULL, tax_rank = \"Family\"),\n  ps_to_long_df(ps_edna_pa, \"eDNA\", families9, lon_var = NULL, tax_rank = \"Family\")\n) %>%\n  filter(!is.na(longitude), longitude >= lon_min, longitude <= lon_max) %>%\n  mutate(lon_bin = cut(longitude, breaks = lon_breaks, include.lowest = TRUE, right = TRUE)) %>%\n  group_by(approach, lon_bin, Family) %>%\n  summarise(pa = as.integer(any(pa == 1)), .groups = \"drop\") %>%\n  mutate(\n    approach = factor(approach, levels = c(\"CPR\", \"eDNA\"))\n  )\n\n# ---- rank families (top = most prevalent across bins and approaches) ----\nfam_rank <- df_binned %>%\n  group_by(Family) %>%\n  summarise(\n    # prevalence across ALL bins/approaches\n    prevalence = sum(pa == 1, na.rm = TRUE),\n    .groups = \"drop\"\n  ) %>%\n  arrange(desc(prevalence), Family)\n\nfam_levels <- fam_rank$Family  # most prevalent first\n\n# ---- apply ordering + fill mapping ----\ndf_binned <- df_binned %>%\n  mutate(\n    Family = factor(Family, levels = fam_levels),  # rows/legend order control\n    fill_family = ifelse(pa == 1, as.character(Family), NA)\n  )\n\n# reorder colours to match the ranked families\nfam_cols_ranked <- fam_cols[fam_levels]\n\n# ---- x-axis labels: bin midpoints ----\nbin_mids <- (lon_breaks[-1] + lon_breaks[-length(lon_breaks)]) / 2\nmid_labels <- sprintf(\"%.2f\", bin_mids)\nnames(mid_labels) <- levels(df_binned$lon_bin)\n\n# ---- plot ----\np <- ggplot(df_binned, aes(x = lon_bin, y = Family, fill = fill_family)) +\n  geom_tile(width = 0.95, height = 0.9, colour = \"grey80\") +\n  facet_wrap(~ approach, ncol = 1) +\n  scale_fill_manual(\n    values = fam_cols_ranked,\n    na.value = \"white\",\n    breaks = fam_levels,\n    limits = fam_levels,\n    drop = FALSE,\n    name = \"Family\"\n  ) +\n  scale_x_discrete(labels = mid_labels) +\n  scale_y_discrete(limits = rev(fam_levels)) +\n  labs(x = \"Longitude section (bin midpoint)\", y = NULL) +\n  theme_minimal(base_size = 12) +\n  theme(\n    panel.grid = element_blank(),\n    strip.text = element_text(face = \"bold\"),\n    axis.text.x = element_text(angle = 45, hjust = 1),\n\n    # 🔹 Remove y-axis completely\n    axis.text.y  = element_blank(),\n    axis.ticks.y = element_blank(),\n    axis.title.y = element_blank()\n  )\n\nprint(p)\n```\n\n::: {.cell-output-display}\n![](Manuscript_analysis_files/figure-html/unnamed-chunk-16-1.png){width=672}\n:::\n:::\n\n\n#### Prevalence scatterplot\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(phyloseq)\nlibrary(gridExtra)\nlibrary(patchwork)\n\n# -----------------------------\n# 1. Shared genera\n# -----------------------------\nshared_genera <- intersect(\n  get_taxa_at_rank(ps_edna_pa, \"Genus\"),\n  get_taxa_at_rank(ps_cpr_pa, \"Genus\")\n)\n\n# -----------------------------\n# 2. Function to calculate genus prevalence\n# -----------------------------\nget_prev <- function(ps, method, genera_keep) {\n  \n  otu <- as(otu_table(ps), \"matrix\")\n  if (!taxa_are_rows(ps)) otu <- t(otu)\n  \n  tax <- as(tax_table(ps), \"matrix\") %>%\n    as.data.frame(check.names = FALSE) %>%\n    rownames_to_column(\"taxa_id\")\n  \n  as.data.frame(otu > 0) %>%\n    rownames_to_column(\"taxa_id\") %>%\n    pivot_longer(\n      -taxa_id,\n      names_to = \"SampleID\",\n      values_to = \"present\"\n    ) %>%\n    left_join(tax, by = \"taxa_id\") %>%\n    mutate(Genus = as.character(Genus)) %>%\n    filter(!is.na(Genus), Genus %in% genera_keep) %>%\n    group_by(SampleID, Genus) %>%\n    summarise(present = any(present), .groups = \"drop\") %>%\n    complete(\n      SampleID = sample_names(ps),\n      Genus = genera_keep,\n      fill = list(present = FALSE)\n    ) %>%\n    group_by(Genus) %>%\n    summarise(\n      prevalence = mean(present) * 100,\n      .groups = \"drop\"\n    ) %>%\n    mutate(method = method)\n}\n\n# -----------------------------\n# 3. Broad taxonomic group\n# -----------------------------\nget_group <- function(ps, genera_keep) {\n  \n  as(tax_table(ps), \"matrix\") %>%\n    as.data.frame(check.names = FALSE) %>%\n    mutate(across(everything(), as.character)) %>%\n    filter(!is.na(Genus), Genus %in% genera_keep) %>%\n    distinct(Genus, Phylum, Class) %>%\n    mutate(\n      broad_group = case_when(\n        Phylum %in% c(\"Arthropoda\", \"Cnidaria\", \"Ctenophora\", \"Mollusca\",\n                      \"Annelida\", \"Chaetognatha\", \"Chordata\", \"Rotifera\",\n                      \"Ciliophora\") ~ \"Zooplankton\",\n        \n        Phylum %in% c(\"Bacillariophyta\", \"Dinoflagellata\", \"Haptophyta\",\n                      \"Ochrophyta\", \"Chlorophyta\", \"Cryptophyta\",\n                      \"Cyanobacteria\") |\n          Class %in% c(\"Mediophyceae\", \"Bacillariophyceae\",\n                       \"Coscinodiscophyceae\", \"Dinophyceae\",\n                       \"Prymnesiophyceae\", \"Dictyochophyceae\",\n                       \"Chlorophyceae\", \"Cryptophyceae\") ~ \"Phytoplankton\",\n        \n        TRUE ~ \"Other/ambiguous\"\n      )\n    ) %>%\n    group_by(Genus) %>%\n    summarise(\n      broad_group = case_when(\n        any(broad_group == \"Zooplankton\") ~ \"Zooplankton\",\n        any(broad_group == \"Phytoplankton\") ~ \"Phytoplankton\",\n        TRUE ~ \"Other/ambiguous\"\n      ),\n      .groups = \"drop\"\n    )\n}\n\n# -----------------------------\n# 4. Combine prevalence and taxonomy\n# -----------------------------\ngenus_prev_df <- bind_rows(\n  get_prev(ps_cpr_pa,  \"CPR\",  shared_genera),\n  get_prev(ps_edna_pa, \"eDNA\", shared_genera)\n) %>%\n  pivot_wider(\n    names_from = method,\n    values_from = prevalence\n  )\n\ngenus_groups <- bind_rows(\n  get_group(ps_cpr_pa, shared_genera),\n  get_group(ps_edna_pa, shared_genera)\n) %>%\n  group_by(Genus) %>%\n  summarise(\n    broad_group = case_when(\n      any(broad_group == \"Zooplankton\") ~ \"Zooplankton\",\n      any(broad_group == \"Phytoplankton\") ~ \"Phytoplankton\",\n      TRUE ~ \"Other/ambiguous\"\n    ),\n    .groups = \"drop\"\n  )\n\nplot_df <- genus_prev_df %>%\n  left_join(genus_groups, by = \"Genus\") %>%\n  arrange(desc(eDNA - CPR)) %>%\n  mutate(\n    taxon_id = row_number(),\n    label = paste0(taxon_id, \". \", Genus)\n  )\n\n# -----------------------------\n# 5. Spearman correlation\n# -----------------------------\ncor_test <- cor.test(\n  plot_df$CPR,\n  plot_df$eDNA,\n  method = \"spearman\"\n)\n\nrho_label <- paste0(\n  \"n = \", nrow(plot_df),\n  \"\\nSpearman \\u03c1 = \", round(unname(cor_test$estimate), 2),\n  \"\\np = \", signif(cor_test$p.value, 2)\n)\n\n# -----------------------------\n# 6. Plot with numbers instead of points\n# -----------------------------\nlibrary(ggplot2)\n\np_fig3 <- ggplot(plot_df, aes(x = CPR, y = eDNA)) +\n    annotate(\n    \"polygon\",\n    x = c(0, 100, 0),\n    y = c(0, 100, 100),\n    fill = \"#DCEAF7\",\n    alpha = 0.4\n  ) +\n\n  annotate(\n    \"polygon\",\n    x = c(0, 100, 100),\n    y = c(0, 0, 100),\n    fill = \"#EEEEEE\",\n    alpha = 0.6\n  ) +\n    annotate(\n    \"text\",\n    x = 55,\n    y = 100,\n    label = \"Higher prevalence\\nin eDNA\",\n    colour = \"#3B6FB6\",\n    fontface = \"italic\",\n    hjust = 0,\n    vjust = 1,\n    size = 4,\n    alpha = 0.8\n  ) +\n  \n  annotate(\n    \"text\",\n    x = 73,\n    y = 60,\n    label = \"Higher prevalence\\nin CPR\",\n    colour = \"grey40\",\n    fontface = \"italic\",\n    hjust = 0,\n    size = 4\n  ) +\n  geom_abline(\n    slope = 1,\n    intercept = 0,\n    linetype = \"dashed\",\n    colour = \"grey55\",\n    linewidth = 0.5\n  ) +\n\n  geom_point(\n    aes(fill = broad_group),\n    shape = 21,\n    size = 6.5,\n    colour = \"black\",\n    stroke = 0.45,\n    alpha = 0.95\n  ) +\n\n  geom_text(\n    aes(label = taxon_id),\n    colour = \"white\",\n    fontface = \"bold\",\n    size = 3.2\n  ) +\n  scale_fill_manual(\n    values = c(\n      \"Zooplankton\"   = \"#D95F02\",  # orange-red\n      \"Phytoplankton\" = \"#1B7837\"   # deep green\n    )\n  ) +\n\n  scale_x_continuous(\n    limits = c(0, 100),\n    breaks = seq(0, 100, 25),\n    expand = expansion(mult = c(0.02, 0.03))\n  ) +\n\n  scale_y_continuous(\n    limits = c(0, 100),\n    breaks = seq(0, 100, 25),\n    expand = expansion(mult = c(0.02, 0.03))\n  ) +\n\n  coord_equal(clip = \"off\") +\n\n  labs(\n    x = \"Prevalence in CPR samples (%)\",\n    y = \"Prevalence in eDNA samples (%)\",\n    title = \"Comparison of genus prevalence between CPR and eDNA\"\n  ) +\n\n  theme_classic(base_size = 13) +\n  theme(\n    plot.title = element_text(face = \"bold\", hjust = 0.5),\n    axis.title = element_text(face = \"bold\"),\n    axis.text = element_text(colour = \"black\"),\n    legend.position = \"bottom\",\n    legend.title = element_blank(),\n    legend.text = element_text(size = 11),\n    legend.key = element_blank(),\n    panel.border = element_rect(colour = \"black\", fill = NA, linewidth = 0.4),\n    plot.margin = margin(8, 12, 8, 8)\n  )\n\np_fig3\n```\n\n::: {.cell-output-display}\n![](Manuscript_analysis_files/figure-html/unnamed-chunk-17-1.png){width=1152}\n:::\n\n```{.r .cell-code}\n# -----------------------------\n# 7. Side list of numbered taxa\n# -----------------------------\n\ntaxa_table <- plot_df %>%\n  arrange(taxon_id) %>%\n  select(taxon_id, Genus)\n\nn <- nrow(taxa_table)\n\ntab1 <- taxa_table[1:ceiling(n/2), ]\ntab2 <- taxa_table[(ceiling(n/2)+1):n, ]\n\ng1 <- tableGrob(tab1, rows = NULL)\ng2 <- tableGrob(tab2, rows = NULL)\n\ntable_plot <- arrangeGrob(\n  g1, g2,\n  ncol = 2\n)\n\np_final <-\n  p_fig3 +\n  wrap_elements(table_plot) +\n  plot_layout(widths = c(2.6, 1.4))\n\np_final\n```\n\n::: {.cell-output-display}\n![](Manuscript_analysis_files/figure-html/unnamed-chunk-17-2.png){width=1152}\n:::\n:::\n\n\n### NMDS\n\n#### CPR\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(phyloseq)\nlibrary(vegan)\nlibrary(tidyverse)\n\nsample_data(ps_cpr)$Water_masses <- ifelse(sample_data(ps_cpr)$Longitude < -10,\n                                       \"Open Ocean\", \"Shelf\")\n\n# Make sure Water_masses is a factor (optional, but useful for consistent plotting)\nsample_data(ps_cpr)$Water_masses <- factor(sample_data(ps_cpr)$Water_masses, \n                                       levels = c(\"Open Ocean\", \"Shelf\"))\n\notu_cpr <- otu_table(ps_cpr)\ntax_cpr <- tax_table(ps_cpr)\nsam_cpr <- sample_data(ps_cpr) \n\n# force taxonomy order to match taxa order \ntax_cpr <- tax_cpr[taxa_names(ps_cpr), ] \n\n# rebuild object\nps_cpr_fixed <- phyloseq(otu_cpr, tax_cpr, sam_cpr)\n\n# ---- extract CPR community matrix ----\nmat_cpr <- as(otu_table(ps_cpr_fixed), \"matrix\")\n\n# samples should be rows, taxa should be columns\nif (taxa_are_rows(ps_cpr_fixed)) {\n  mat_cpr <- t(mat_cpr)\n}\n\n# ---- convert to presence/absence ----\nmat_cpr_pa <- (mat_cpr > 0) * 1\n\n# remove taxa absent from all samples\nmat_cpr_pa <- mat_cpr_pa[, colSums(mat_cpr_pa) > 0, drop = FALSE]\n\n# remove samples with no taxa detected, if any\nmat_cpr_pa <- mat_cpr_pa[rowSums(mat_cpr_pa) > 0, , drop = FALSE]\n\n# ---- NMDS using Jaccard distance ----\nset.seed(123)\n\nnmds_cpr <- metaMDS(\n  mat_cpr_pa,\n  distance = \"jaccard\",\n  binary = TRUE,\n  k = 2,\n  trymax = 200,\n  autotransform = FALSE,\n  trace = FALSE\n)\n\n# ---- extract NMDS scores ----\nscores_cpr <- as.data.frame(scores(nmds_cpr, display = \"sites\")) %>%\n  rownames_to_column(\"SampleID\")\n\n# ---- extract metadata ----\nmeta_cpr <- as(sample_data(ps_cpr_fixed), \"data.frame\") %>%\n  rownames_to_column(\"SampleID\")\n\n# keep only samples used in NMDS\nmeta_cpr <- meta_cpr %>%\n  filter(SampleID %in% rownames(mat_cpr_pa))\n\nplot_cpr <- scores_cpr %>%\n  left_join(meta_cpr, by = \"SampleID\")\n\nggplot(\n  plot_cpr,\n  aes(\n    x = NMDS1,\n    y = NMDS2,\n    colour = Water_masses\n  )\n) +\n  geom_point(size = 3, alpha = 0.7) +\n  stat_ellipse(\n    aes(group = Water_masses),\n    linewidth = 0.8,\n    linetype = \"dashed\"\n  ) +\n  scale_colour_manual(\n    values = c(\n      \"Open Ocean\" = \"#D55E00\",\n      \"Shelf\" = \"#0072B2\"\n    )\n  ) +\n  coord_equal(\n    xlim = c(-1.3, 1.0),\n    ylim = c(-1.3, 1.0)\n  ) +\n  theme_minimal(base_size = 12)\n```\n\n::: {.cell-output-display}\n![](Manuscript_analysis_files/figure-html/unnamed-chunk-18-1.png){width=672}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nadonis2(\n  mat_cpr_pa ~ Water_masses,\n  data = meta_cpr,\n  method = \"jaccard\",\n  binary = TRUE,\n  permutations = 999\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nPermutation test for adonis under reduced model\nPermutation: free\nNumber of permutations: 999\n\nadonis2(formula = mat_cpr_pa ~ Water_masses, data = meta_cpr, permutations = 999, method = \"jaccard\", binary = TRUE)\n         Df SumOfSqs      R2     F Pr(>F)    \nModel     1   0.9843 0.09517 3.576  0.001 ***\nResidual 34   9.3584 0.90483                 \nTotal    35  10.3427 1.00000                 \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndist_cpr <- vegdist(\n  mat_cpr_pa,\n  method = \"jaccard\",\n  binary = TRUE\n)\n\ndisp_cpr <- betadisper(\n  dist_cpr,\n  meta_cpr$Water_masses\n)\n\nanova(disp_cpr)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAnalysis of Variance Table\n\nResponse: Distances\n          Df   Sum Sq  Mean Sq F value   Pr(>F)   \nGroups     1 0.061634 0.061634  9.6829 0.003755 **\nResiduals 34 0.216416 0.006365                    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n\n```{.r .cell-code}\npermutest(disp_cpr)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nPermutation test for homogeneity of multivariate dispersions\nPermutation: free\nNumber of permutations: 999\n\nResponse: Distances\n          Df   Sum Sq  Mean Sq      F N.Perm Pr(>F)   \nGroups     1 0.061634 0.061634 9.6829    999  0.003 **\nResiduals 34 0.216416 0.006365                        \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\n#### eDNA NMDS at genus level\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(phyloseq)\nlibrary(vegan)\nlibrary(tidyverse)\n\nsample_data(ps_edna)$Water_masses <- ifelse(sample_data(ps_edna)$lon < -10,\n                                       \"Open Ocean\", \"Shelf\")\n\n# Make sure Water_masses is a factor (optional, but useful for consistent plotting)\nsample_data(ps_edna)$Water_masses <- factor(sample_data(ps_edna)$Water_masses, \n                                       levels = c(\"Open Ocean\", \"Shelf\"))\n\n# -------------------------\n# Aggregate to Genus level\n# -------------------------\n\nps_edna_genus <- tax_glom(\n  ps_edna,\n  taxrank = \"Genus\",\n  NArm = TRUE\n)\n\n# -------------------------\n# Extract matrix\n# -------------------------\n\nmat_genus <- as(otu_table(ps_edna_genus), \"matrix\")\n\nif (taxa_are_rows(ps_edna_genus)) {\n  mat_genus <- t(mat_genus)\n}\n\n# -------------------------\n# Presence / absence\n# -------------------------\n\nmat_genus_pa <- (mat_genus > 0) * 1\n\n# Remove empty taxa\nmat_genus_pa <- mat_genus_pa[\n  ,\n  colSums(mat_genus_pa) > 0,\n  drop = FALSE\n]\n\n# Remove empty samples\nmat_genus_pa <- mat_genus_pa[\n  rowSums(mat_genus_pa) > 0,\n  ,\n  drop = FALSE\n]\n\ndim(mat_genus_pa)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1]  85 366\n```\n\n\n:::\n\n```{.r .cell-code}\n# -------------------------\n# NMDS\n# -------------------------\n\nset.seed(123)\n\nnmds_edna_genus <- metaMDS(\n  mat_genus_pa,\n  distance = \"jaccard\",\n  binary = TRUE,\n  k = 2,\n  trymax = 200,\n  autotransform = FALSE,\n  trace = FALSE\n)\n\nnmds_edna_genus$stress\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.1060012\n```\n\n\n:::\n\n```{.r .cell-code}\nscores_edna_genus <- as.data.frame(\n  scores(nmds_edna_genus, display = \"sites\")\n) %>%\n  rownames_to_column(\"SampleID\")\n\nmeta_edna <- as(sample_data(ps_edna), \"data.frame\") %>%\n  rownames_to_column(\"SampleID\")\n\nplot_edna_genus <- left_join(\n  scores_edna_genus,\n  meta_edna,\n  by = \"SampleID\"\n)\n\np_edna_genus <- ggplot(\n  plot_edna_genus,\n  aes(\n    NMDS1,\n    NMDS2,\n    colour = Water_masses\n  )\n) +\n  geom_point(size = 3, alpha = 0.7) +\n  stat_ellipse(\n    aes(group = Water_masses),\n    linewidth = 0.8,\n    linetype = \"dashed\"\n  ) +\n  scale_colour_manual(\n    values = c(\n      \"Open Ocean\" = \"#D55E00\",\n      \"Shelf\" = \"#0072B2\"\n    )\n  ) +\n  coord_equal(\n    xlim = c(-1.3, 1.0),\n    ylim = c(-1.3, 1.0)\n  ) +\n  labs(\n    title = \"eDNA (Metabarcoding)\",\n    colour = NULL\n  ) +\n  theme_minimal(base_size = 12)\n\np_edna_genus\n```\n\n::: {.cell-output-display}\n![](Manuscript_analysis_files/figure-html/unnamed-chunk-21-1.png){width=672}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nadonis2(\n  mat_genus_pa ~ Water_masses,\n  data = meta_edna,\n  method = \"jaccard\",\n  binary = TRUE,\n  permutations = 999\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nPermutation test for adonis under reduced model\nPermutation: free\nNumber of permutations: 999\n\nadonis2(formula = mat_genus_pa ~ Water_masses, data = meta_edna, permutations = 999, method = \"jaccard\", binary = TRUE)\n         Df SumOfSqs      R2      F Pr(>F)    \nModel     1   2.1258 0.16986 16.983  0.001 ***\nResidual 83  10.3895 0.83014                  \nTotal    84  12.5153 1.00000                  \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndist_genus <- vegdist(\n  mat_genus_pa,\n  method = \"jaccard\",\n  binary = TRUE\n)\n\ndisp_genus <- betadisper(\n  dist_genus,\n  meta_edna$Water_masses\n)\n\nanova(disp_genus)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAnalysis of Variance Table\n\nResponse: Distances\n          Df  Sum Sq Mean Sq F value    Pr(>F)    \nGroups     1 0.47005 0.47005  82.619 4.323e-14 ***\nResiduals 83 0.47221 0.00569                      \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n\n```{.r .cell-code}\npermutest(disp_genus)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nPermutation test for homogeneity of multivariate dispersions\nPermutation: free\nNumber of permutations: 999\n\nResponse: Distances\n          Df  Sum Sq Mean Sq      F N.Perm Pr(>F)    \nGroups     1 0.47005 0.47005 82.619    999  0.001 ***\nResiduals 83 0.47221 0.00569                         \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\n### Unique to CPR vs unique to eDNA\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(phyloseq)\n\n# -----------------------------\n# 1. Helper: extract genera present in a phyloseq object\n# -----------------------------\n\nget_present_genera <- function(ps) {\n\n  tax <- as(tax_table(ps), \"matrix\") %>%\n    as.data.frame(check.names = FALSE)\n\n  present_taxa <- taxa_names(ps)[taxa_sums(ps) > 0]\n\n  tax[present_taxa, \"Genus\"] %>%\n    as.character() %>%\n    purrr::discard(~ is.na(.x) |\n              .x == \"\" |\n              .x == \"N/A\" |\n              .x == \"NA\" |\n              .x == \"Unknown\") %>%\n    unique()\n}\n\nedna_genera <- get_present_genera(ps_edna)\ncpr_genera  <- get_present_genera(ps_cpr)\n\nshared_genera   <- intersect(edna_genera, cpr_genera)\ncpr_only_genera <- setdiff(cpr_genera, edna_genera)\nedna_only_genera <- setdiff(edna_genera, cpr_genera)\n\ngenus_overlap_counts <- tibble(\n  category = c(\"Shared\", \"CPR only\", \"eDNA only\"),\n  n_genera = c(\n    length(shared_genera),\n    length(cpr_only_genera),\n    length(edna_only_genera)\n  )\n)\n\ngenus_overlap_counts\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 2\n  category  n_genera\n  <chr>        <int>\n1 Shared          40\n2 CPR only        48\n3 eDNA only      326\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 20 × 5\n   Genus              n_present n_samples prevalence category\n   <chr>                  <int>     <int>      <dbl> <chr>   \n 1 Ceratium                  33        36      91.7  CPR only\n 2 Para-Pseudocalanus        28        36      77.8  CPR only\n 3 Emiliania                 19        36      52.8  CPR only\n 4 Dictyocysta               18        36      50    CPR only\n 5 Rhabdosphaera             14        36      38.9  CPR only\n 6 Proboscia                 11        36      30.6  CPR only\n 7 Oxytoxum                   9        36      25    CPR only\n 8 Corycaeus                  8        36      22.2  CPR only\n 9 Lepas                      7        36      19.4  CPR only\n10 Spiniferites               7        36      19.4  CPR only\n11 Cylindrotheca              4        36      11.1  CPR only\n12 Acanthoica                 3        36       8.33 CPR only\n13 Odontella                  3        36       8.33 CPR only\n14 Pronoctiluca               3        36       8.33 CPR only\n15 Pseudo-nitzschia           3        36       8.33 CPR only\n16 Stenosemella               3        36       8.33 CPR only\n17 Alteutha                   2        36       5.56 CPR only\n18 Coccolithus                2        36       5.56 CPR only\n19 Dadayiella                 2        36       5.56 CPR only\n20 Euchaetidae                2        36       5.56 CPR only\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 20 × 5\n   Genus             n_present n_samples prevalence category \n   <chr>                 <int>     <int>      <dbl> <chr>    \n 1 Biecheleria              85        85      100   eDNA only\n 2 Gephyrocapsa             85        85      100   eDNA only\n 3 Haptolina                85        85      100   eDNA only\n 4 Karenia                  85        85      100   eDNA only\n 5 Karlodinium              85        85      100   eDNA only\n 6 Lepidodinium             85        85      100   eDNA only\n 7 Cyrtostrombidium         84        85       98.8 eDNA only\n 8 Gyrodinium               84        85       98.8 eDNA only\n 9 Torodinium               84        85       98.8 eDNA only\n10 Bathycoccus              83        85       97.6 eDNA only\n11 Goniomonas               81        85       95.3 eDNA only\n12 Paragymnodinium          81        85       95.3 eDNA only\n13 Protaspa                 81        85       95.3 eDNA only\n14 Chrysochromulina         79        85       92.9 eDNA only\n15 Aplanochytrium           78        85       91.8 eDNA only\n16 Phaeocystis              77        85       90.6 eDNA only\n17 Biecheleriopsis          76        85       89.4 eDNA only\n18 Blastodinium             76        85       89.4 eDNA only\n19 Pentapharsodinium        76        85       89.4 eDNA only\n20 Prymnesium               76        85       89.4 eDNA only\n```\n\n\n:::\n:::\n\n\n### Investigating the top 20 most prevalent eDNA-only taxa\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntax_edna <- as.data.frame(tax_table(ps_edna))\n\nedna_only_taxonomy <- tax_edna %>%\n  filter(Genus %in% edna_only_genera) %>%\n  select(\n    Phylum,\n    Class,\n    Order,\n    Family,\n    Genus\n  ) %>%\n  distinct()\n\nrownames(edna_only_taxonomy) <- NULL\n\nedna_only_summary <- edna_only_prev %>%\n  left_join(\n    edna_only_taxonomy,\n    by = \"Genus\"\n  ) %>%\n  arrange(desc(prevalence))\n\nhead(edna_only_summary, 30)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 30 × 9\n   Genus       n_present n_samples prevalence category Phylum Class Order Family\n   <chr>           <int>     <int>      <dbl> <chr>    <chr>  <chr> <chr> <chr> \n 1 Biecheleria        85        85      100   eDNA on… Myzoz… Dino… Sues… Biech…\n 2 Gephyrocap…        85        85      100   eDNA on… Hapto… Cocc… Isoc… Noela…\n 3 Haptolina          85        85      100   eDNA on… Hapto… Cocc… Prym… Prymn…\n 4 Karenia            85        85      100   eDNA on… Myzoz… Dino… Gymn… Brach…\n 5 Karlodinium        85        85      100   eDNA on… Myzoz… Dino… Gymn… Karen…\n 6 Lepidodini…        85        85      100   eDNA on… Myzoz… Dino… Gymn… Gymno…\n 7 Cyrtostrom…        84        85       98.8 eDNA on… Cilio… Olig… Olig… Cyrto…\n 8 Gyrodinium         84        85       98.8 eDNA on… Myzoz… Dino… Gymn… Gymno…\n 9 Torodinium         84        85       98.8 eDNA on… Myzoz… Dino… Gymn… Gymno…\n10 Bathycoccus        83        85       97.6 eDNA on… Chlor… Mami… Mami… Bathy…\n# ℹ 20 more rows\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nclass_edna_summary <- edna_only_summary %>% group_by(Class) %>% summarise( n_genera = n_distinct(Genus), mean_prevalence = mean(prevalence), .groups = \"drop\" ) %>% arrange(desc(n_genera))\n\nclass_plot_df <- class_edna_summary %>%\n  filter(mean_prevalence > 10, n_genera >= 5) %>%\n  arrange(desc(n_genera)) %>%\n  slice_head(n = 15) %>%   # adjust if you want more/fewer classes\n  mutate(\n    Class = forcats::fct_reorder(Class, n_genera)\n  )\n\np_edna_only_classes <- ggplot(\n  class_plot_df,\n  aes(\n    x = n_genera,\n    y = Class,\n    fill = mean_prevalence\n  )\n) +\n  geom_col(width = 0.75) +\n  geom_text(\n    aes(label = n_genera),\n    hjust = -0.25,\n    size = 3.5\n  ) +\n  scale_fill_gradient(\n    low = \"grey85\",\n    high = \"black\",\n    name = \"Mean\\nprevalence (%)\"\n  ) +\n  scale_x_continuous(\n    expand = expansion(mult = c(0, 0.15))\n  ) +\n  labs(\n    x = \"Number of genera detected only by eDNA\",\n    y = NULL,\n    title = \"Taxonomic classes containing genera uniquely detected by eDNA\"\n  ) +\n  theme_minimal(base_size = 12) +\n  theme(\n    panel.grid.major.y = element_blank(),\n    panel.grid.minor = element_blank(),\n    plot.title = element_text(face = \"bold\")\n  )\n\np_edna_only_classes\n```\n\n::: {.cell-output-display}\n![](Manuscript_analysis_files/figure-html/unnamed-chunk-27-1.png){width=672}\n:::\n:::\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<script src=\"site_libs/kePrint-0.0.1/kePrint.js\"></script>\n<link href=\"site_libs/lightable-0.0.1/lightable.css\" rel=\"stylesheet\" />\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}